### ISSUE TITLE
Live Visualizer bug after hooks updates

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#1033]
It looks like something accidentally changed in the API with the move of `live_visualizer` to a hook in #911. This shows up in the OPS tutorial, [notebook 4](https://github.com/openpathsampling/ops_tutorial/blob/main/4_mstis_sampling_tutorial.ipynb) (which is very similar to the MSTIS example in the core OPS docs).

The cell giving the error, and the resulting error, are:

```python
xval = paths.FunctionCV("xval", lambda snap : snap.xyz[0][0])
yval = paths.FunctionCV("yval", lambda snap : snap.xyz[0][1])
mstis_calc.live_visualizer = paths.StepVisualizer2D(
    network=mstis, 
    cv_x=xval, 
    cv_y=yval,
    xlim=[-1.0, 1.0],
    ylim=[-1.0, 1.0]
)
background = ToyPlot()
background.contour_range = np.arange(-1.5, 1.0, 0.1)
background.add_pes(engine.pes)
mstis_calc.live_visualizer.background = background.plot()
mstis_calc.status_update_frequency = 1 # increasing this number speeds things up, but isn't as pretty
```

```pytb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-9dcf20c9eec3> in <module>
     11 background.contour_range = np.arange(-1.5, 1.0, 0.1)
     12 background.add_pes(engine.pes)
---> 13 mstis_calc.live_visualizer.background = background.plot()
     14 mstis_calc.status_update_frequency = 1 # increasing this number speeds things up, but isn't as pretty

AttributeError: 'NoneType' object has no attribute 'background'
```

I haven't looked into the code yet, but it looks like there's probably a problem with the `@property` for `live_visualizer`.

@hejung : If you happen to have time to look into this today, please let me know by replying to this issue. Otherwise, I'll take a look later today (I bet the fix will be pretty easy). I'm currently working on fixing another bug, so I'm hoping for a mid-week 1.5.1 bugfix release to include this and the other fix I'm working on.

The principle here is that the old API should still work. However, I will be updating the tutorial notebooks to use the better approach enabled by #911: see https://github.com/openpathsampling/ops_tutorial/issues/16.

**Comment by hejung** [comment]
I think I found the issue (I did not set the `self._live_visualizer` in the `property.setter`). I am preparing a fix, will submit it later today.
