### ISSUE TITLE
Cool logo

### ISSUE THREAD

**Issue by jchodera** [openpathsampling/openpathsampling#134]
You guys also need a cool logo!

**Comment by dwhswenson** [comment]
The first thing that comes to mind is something like the attached, which attempts to use the O and the rounded part of the P in OPS as "states", and the S as part of a "path" connecting them. Two versions attached: one  initials, one words (personally, I like the words more). Just a rough first idea; obviously this isn't pretty (we'd color the "states", bold the letters, taper from the S to the "path" parts, and use better fonts than my handwriting with my index finger on an iPad). But it's one idea. There are probably much better ideas out there, so I'm completely open to very different options.
![ops - 20150129_015637 - 1](https://cloud.githubusercontent.com/assets/8178546/5950554/1ffc734a-a75c-11e4-91d1-af4a06d4e9c5.png)

(Sadly, my recent date with someone who designs logos for a living was only a *first* date, and I don't think asking her to do the OPS logo is a good plan for our second date.)

**Comment by bolhuis** [comment]
Hi,

I have this drawing  lying around.






with a text


Keynote attached. Please feel free to play around

P




On 29 Jan 2015, at 02:15, David W.H. Swenson <notifications@github.com> wrote:

> The first thing that comes to mind is something like the attached, which attempts to use the O and the rounded part of the P in OPS as "states", and the S as part of a "path" connecting them. Two versions attached: one initials, one words (personally, I like the words more). Just a rough first idea; obviously this isn't pretty (we'd color the "states", bold the letters, taper from the S to the "path" parts, and use better fonts than my handwriting with my index finger on an iPad). But it's one idea. There are probably much better ideas out there, so I'm completely open to very different options.
> 
> 
> (Sadly, my recent date with someone who designs logos for a living was only a first date, and I don't think asking her to do the OPS logo is a good plan for our second date.)
> 
> —
> Reply to this email directly or view it on GitHub.
> 


prof. dr. Peter Bolhuis	

Amsterdam Center for Multiscale Modeling
Computational Chemistry and Physics
van 't Hoff Institute for Molecular Sciences (HIMS)
University of Amsterdam
PO Box 94157
1090 GD Amsterdam, The Netherlands

phone: +31-205256447
email: p.g.bolhuis@uva.nl

**Comment by jhprinz** [comment]
I might have little money from the DAAD that I could spend on asking someone to create a logo, etc for us. I was thinking of Thomas Splettstösser www.scistyle.com. He is a former collegue from the group of Jeremy Smith.

**Comment by jchodera** [comment]
That would be awesome!  We might be able to help fund this so that JHP doesn't have to use his DAAD funds on this.

**Comment by jhprinz** [comment]
I just thought that I think I get like 300€ from the DAAD for lab related stuff that I have to ask for, but that is not the case. I will ask Thomas and see if he has time. The other cool site that David suggested was 99designs, which might be good for other projects, too. You post what you need and get proposals from designers and can pick a 'winner'. The results looked pretty nice.

**Comment by dwhswenson** [comment]
As JHP and I discussed in our Skype call, I'm also in favor of first seeing if Thomas can do this. 

But if we instead use 99designs, we should keep an eye out for a promo code. They are frequent advertisers on some podcasts I listen to, and if I remember correctly, their promo is a free upgrade from one tier of service to the next. (Or maybe it was X% off; either way, worth taking advantage of if we go that direction.)

**Comment by dwhswenson** [comment]
I threw something together based on my previous sketch, just to use temporarily in my upcoming talk.

Oh, and I'll claim to have no idea who this Mondriaan you're referring to is, nor do I know anything about any stijl.

![opslogo](https://cloud.githubusercontent.com/assets/8178546/11313286/bdab3fe6-8fa9-11e5-9762-b18252ec19ed.png)

**Comment by jhprinz** [comment]
I contacted Thomas Splettstoesser. Let's if he can do something.

**Comment by jhprinz** [comment]
Splette answered Spain, but will be back next week in Berlin and I can meet him to discuss making a logo. @jchodera, @bolhuis and @franknoe. Maybe not discuss in public but I think we said that there is some money for this. Can anyone give me an idea what I can offer money wise?

**Comment by jhprinz** [comment]
This is in the works... Let you know when we have something to look at.

**Comment by jhprinz** [comment]
"it is done..." - We have a new logo. Our secretary just confirmed that we paid Thomas Splettstösser for the new logo. Thanks to www.scistyle.com for the great work. I consider this finally closed and will send you all the new logo to be used! Hooray...

**Comment by dwhswenson** [comment]
I'll call it officially done once I get that copy of it ;-) (probably won't be able to slide a mention of OPS into my talk tomorrow, though)

**Comment by jchodera** [comment]
So...where's the logo?

**Comment by jhprinz** [comment]
Just send it by mail...

**Comment by dwhswenson** [comment]
And @jhprinz even changed the GitHub org logo. This issue is closed!
