### ISSUE TITLE
Docstring cleanup

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#151]
Looking at the output of our docs, I think we need to go over our docstrings and bring them into proper numpydoc format.

Two main types of changes that I’ve noticed we need to make:
- start each docstring with the brief description: aim to keep it on an 80-column terminal
- correct listing of types in parameter blocks

We have REALLY bad "brief" docstrings. They aren’t brief. When Sphinx generates tables of classes/functions, it puts the function name on the left, and the brief description on the right. But it forces everything to be on one line. So if the "brief" description is long, you have to scroll horizontally to read it. That’s annoying.

We won’t be able to remove all scrolling on laptops, but we should minimize it. Hence my suggestion of a description that fits on an 80-char width terminal.

I’m currently modifying a number of docstrings to match this behavior as part of my `docs_cleanup` branch. 

[Details of numpydoc format](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt)

**Comment by jhprinz** [comment]
I fully agree, most docstrings are not as they should. Especially the short summary. I will try to be aware of that for further changes. The summary is very good.

**Comment by dwhswenson** [comment]
While there's always room for improvement, I think this no longer needs to be an open issue. Closing!
