### ISSUE TITLE
Topology as part of engine?

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#311]
I was wondering if it makes sense to attach a topology only to an `Engine` and let each generated `Snapshot` point to the engine that made it. 

This means a snapshot is not complete (at least topology wise) without its engine! On the other hand we could have snapshots without topologies since we could think about engines that are not MD and might not use the concept of a topology. It goes in the direction of abstract snapshots with no special properties of than comprising trajectories. 

To me this seems to make sense, but I not sure.

To create Snapshots from files like `.pdb` we could have special engine that just creates snapshots, transforms them, etc.

**Comment by dwhswenson** [comment]
If I recall, right now every `Snapshot` has a `topology` parameter. If I understand, you're saying to instead switch that to an `engine`, meaning that each `DynamicsEngine` must be associated with a single `topology`. Then `Snapshot.topology` can just be a shortcut for `Snapshot.engine.topology`.

All of this sounds fine to me, although you're talking about creating the ability to translate between topologies for different engines, which scales as $N^2$ in the number of engines. Fine when all the engines are very similar, but what if your snapshot needs extra information (e.g., from QM)? Then it gets messy. You would have to define every "class" of dynamics you want to do, and define a way to translate snapshots between those classes. That's still $N^2$, but a smaller $N$. On the other hand, if the goal is to keep OPS useful in general (beyond MD) then there's no way you can enumerate all such classes. I'm not sure its even possible within MD: there are too many possible "extra objects" to hold.

Also, isn't this pretty much #208/#197? Do we need a separate issue?

**Comment by dwhswenson** [comment]
This will be handled in #380, right?

**Comment by jhprinz** [comment]
No. I removed that to keep the PRs really separate now.

**Comment by jhprinz** [comment]
Will be part of upcoming engine / snapshot restructuring.
