### ISSUE TITLE
Move repo to its own organization

### ISSUE THREAD

**Issue by franknoe** [openpathsampling/openpathsampling#313]
Can we move this Repo to an organization openpathsampling ? That would be better to get multiple groups involved, plus we can organize multiple subsidiary packages or paper repos under this roof.

**Comment by jchodera** [comment]
This is fine with me.

**Comment by dwhswenson** [comment]
I think this is a good idea, but I think we should do it once the API is settled. Right now things are so fluid that I fear we'd frustrate anyone who wants to play with it.

My preference: move to a new org shortly before we submit the papers.

**Comment by dwhswenson** [comment]
As I said earlier on this issue: I think moving the repo to its own org is a good idea, but I think it should wait until our API is reasonably stable and we’re approaching a 1.0 release.

And now, I think our API is reasonably stable, and we’re approaching a 1.0 release.

Plus, @jhprinz and I decided that the twins’ birthday would be a good day to make it official! (It *is* after midnight in our time zone.)

So I’ve created the organization, and invited @jhprinz, @jchodera, @bolhuis, and @franknoe to join it as owners. @jhprinz: Will you do the honors of officially moving the repository to the new organization? (Settings tab at the top; scroll down to "Danger Zone" and then "Transfer".)

Then it’ll be official, and this issue can be closed! :-)

**Comment by franknoe** [comment]
Thanks!

Am 13/06/16 um 00:02 schrieb David W.H. Swenson:
>
> As I said earlier on this issue: I think moving the repo to its own 
> org is a good idea, but I think it should wait until our API is 
> reasonably stable and we’re approaching a 1.0 release.
>
> And now, I think our API is reasonably stable, and we’re approaching a 
> 1.0 release.
>
> Plus, @jhprinz <https://github.com/jhprinz> and I decided that the 
> twins’ birthday would be a good day to make it official! (It /is/ 
> after midnight in our time zone.)
>
> So I’ve created the organization, and invited @jhprinz 
> <https://github.com/jhprinz>, @jchodera <https://github.com/jchodera>, 
> @bolhuis <https://github.com/bolhuis>, and @franknoe 
> <https://github.com/franknoe> to join it as owners. @jhprinz 
> <https://github.com/jhprinz>: Will you do the honors of officially 
> moving the repository to the new organization? (Settings tab at the 
> top; scroll down to "Danger Zone" and then "Transfer".)
>
> Then it’ll be official, and this issue can be closed! :-)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/choderalab/openpathsampling/issues/313#issuecomment-225463214>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AGMeQgv6J1BmU2_iu1r0gRuEQ8zq2rPaks5qLIIRgaJpZM4F_7yG>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by jhprinz** [comment]
Thanks David. Will do this switch today when I find the big red button! Woohoo...

**Comment by jhprinz** [comment]
"It is done."
