### ISSUE TITLE
Rename LiveVisualization

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#326]
I originally made the `LiveVisualization` so that it could be used to watch the results in a notebook as they come in. However, it also works very well for visualizing trajectories in general, and isn't limited to only the live results.

I'm thinking maybe `LiveVisualization` => `TrajectoryVisualization2D`? Open to other suggestions.

**Comment by jhprinz** [comment]
This is very useful and I already used this partially for making plots. Whatabout having a submodule visualization and then
```
import openpathsampling.visualization as vis
vis.Trajectory2D()
vis.PathMoverTree()
```
and so on...

**Comment by dwhswenson** [comment]
If we make such a module, how do we decide what does/does not go into it? For classes that are visualization-only, that's easy. But what about things like the replica exchange graphs, where visualization is just one method in a much larger class? Choices would be:

* leave that as is, and outside of visualization
* separate the visualization into a separate function that takes the object as argument

I think either of these is reasonable. I don't think that including non-visualization analysis in the visualization submodule would be reasonable.

**Comment by dwhswenson** [comment]
I'll eventually take care of this, but we should discuss what exactly the best to do, especially regarding a possible subpackage/module approach. Thoughts, @jhprinz?

**Comment by dwhswenson** [comment]
On discussion tonight: I will move the repex networkx-based visualization into a function that takes the analysis object as an argument.

**Comment by dwhswenson** [comment]
Further discussion of this in #527; closing this issue.
