### ISSUE TITLE
Visualization questions and cleanup suggestions

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#337]
Looking more closely at these new visualizations, and there are a few issues I'd like to see resolved.
1. This should be one line per **_canonical**_ move. Separating the minus move into multiple steps is just confusing. At the very least, there needs to be an option for this.
2. How do I turn off showing replica exchange? Or turn off showing minus moves? This is what we'd usually want to look at. And if, after a minus move, the next path might be completely decorrelated: that's fine. It should be like starting a new tree with the decorrelated segment of the minus trajectory.
3. What are the numbers to the left? Can I turn them off? The representation of the move should be labelled with the step number, and possibly a short string to identify move type (I mostly agree with your selections: "f", "b", "r", "x", and I'd use "-" for the minus move; possibly "f-"/"b-" to differentiate direction.) Other numbers are just confusing. I think the number you have next to the path is actually _not_ the step number -- step number is at the far left now, right? (All these differences from the behavior of old scripts will only confuse users -- let's keep things as similar as possible.)
4. How do I get this to show rejected moves? That was one of the most useful new aspects of this visualization in a previous version. Now I don't see any difference when I set `tree.rejected=True`.

I think you might be losing sight of the way we actually use these "path tree" visualizations. The purpose is _not_ to be a log of every substep of the move, tracking provenance. Rather, it gives important information on how paths are decorrelating. The current version of these includes a bunch of visual "extras" that distract from the point.

Examples of the kinds of information that we get from these pictures:
- _Does the path length oscillate between different characteristic lengths?_ This could indicate switching between two mechanisms.
- _Do we see blocks where one direction of shooting is consistently rejected?_ This tells us something about early-vs-late barriers in the system.
- _Do rejected shooting moves from a particular region have much longer trajectories that still end in the states?_ Again, this suggests multiple channels, and may indicate that we're completely missing one channel.

These are just a few sorts of things I've thought of in past while looking at these plots. That doesn't mean the list is exclusive. The point is that asymmetries in the tree can inspire us to ask questions about why. Those are easier to catch if the visualization is less information-dense.
---

As an aside, #335 includes a subclass for the move tree visualization in order to simplify for the common case. It makes the user's tasks (which are what the notebooks are to illustrate) much easier.

**Comment by jhprinz** [comment]
Will address this in #400 .

**Comment by jhprinz** [comment]
Can this be closed? I am not sure if I cover exactly everything in here in the Vis update PR.

**Comment by jhprinz** [comment]
Add more examples to `visualization_tutorial.ipynb`

**Comment by dwhswenson** [comment]
Just to clarify: what I'd really like to see to solve this issue are some clearer pictures in [`tutorial_path_tree_visualization.ipynb`](https://github.com/openpathsampling/openpathsampling/blob/8b607a77d258e938bd2cc77fe99c9896b90cd323/examples/misc/tutorial_pathtree_visualization.ipynb).

Problems with that current example:

1. The examples use *all* the steps. While it looks pretty cool with the whole simulation there, it's really hard to tell the difference between different visualizations.

2. You don't include visualizations of the effect that some options have. For example, there's no picture associated with `flip_time_direction` or `joined_blocks`. A lot of the other descriptions will be a lot more clear if you used pictures to explain it. It also isn't clear how to show rejected moves transparent vs. how to not show them at all.

Anyway, these are the things that I think are needed to close this issue (much easier than writing a whole new notebook, and much more useful!)
