### ISSUE TITLE
RuntimeError: 0 minus movers for the same ensemble?

### ISSUE THREAD

**Issue by Asagodi** [openpathsampling/openpathsampling#421]
After I changed the scripts to the new functions and settings all analyses (except for one) prompted this error when trying to do the rate calculations:

https://gist.github.com/Asagodi/31756aaf243e9fb22f64#file-4c_analysis3_0-ipynb

Is there something I miss when updating the scripts to do the simulations or the bootstrapping?

**Comment by dwhswenson** [comment]
This probably means that, for at least one of your transitions, the minus mover is never used. I can't tell any more without seeing the set-up of the network. Try looking at the output of `scheme.move_summary(storage, 'minus')`.

**Comment by dwhswenson** [comment]
Closed under the heading of "Abel has finished his bachelor's project, so any help now is coming too late."
