### ISSUE TITLE
Setup of outer and minus ensembles for MISTIS

### ISSUE THREAD

**Issue by Asagodi** [openpathsampling/openpathsampling#424]
How should I create the outer and minus ensemble in a system with 4 states where I would like to calculate the rate for all 12 transitions? Also I would like to investigate two different interface sets for one of the transitions.

I tried to set it up as in the TIS example, but didn't succeed:
https://gist.github.com/Asagodi/a7efbf6206576861b6f2#file-4_mistis_run-ipynb

**Comment by dwhswenson** [comment]
Closed under the heading of "Abel has finished his bachelor's project, so any help now if coming too late."
