### ISSUE TITLE
Request Lammps to provide precompiled binary with Python support enabled

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#427]
Guess that would be easier than building it on travis...

**Comment by dwhswenson** [comment]
Maybe. But from the LAMMPS site, it looks like they rely on 3rd parties (i.e., *us*) to generate/host such precompiled binaries. Reading through the various installs on [the download page](http://lammps.sandia.gov/download.html), it sounds like each individual install approach is managed by a specific person. Some are by active devs, but many of the people aren't even on the authors list. In particular, the Ubuntu/Debian package is from a guy who, as far as I can tell, does general scientific computing and may just work for Debian ([the maintainer of the package is the Debian Science Maintainers team](https://tracker.debian.org/pkg/lammps) -- it may be best to contact them about changing the package build script.)

It doesn't hurt to ask, but I wouldn't be surprised if the response from either the LAMMPS people or from the current package maintainer is "do it yourself," and, if we're lucky, they'll say "and we'll host the result."

LAMMPS has a [Travis script](https://github.com/lammps/lammps/blob/lammps-icms/.travis.yml), so in principle we could modify that script to push the binary somewhere. They might even work with us to put that into their main Travis and maybe even let us put the binary on their server.

**Comment by dwhswenson** [comment]
Closing this. LAMMPS is on conda-forge: https://github.com/conda-forge/lammps-feedstock/
