### ISSUE TITLE
More ipynb cleanup

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#447]
This follows on #446. There were a few things I wasn't sure how to fix from some of @jhprinz's notebooks. Rather than do something that might not match the original intent of the notebook, I'm leaving these for @jhprinz.

NOTE: you should only work on this *after* merging #446. I've already made a few changes to these notebooks to give partial fixes. There are just a few cells left where I don't know what you want.

Two notebooks have problems:

#### `storage_mem_test.ipynb`

The problem is in cell 15. It looks like all values that you calculated in `dd2` are zero. All other cells run fine.

#### `tutorial_visualization.ipynb`

* First problem: cell 5. Toy snapshots no longer have `configuration`s. Switching `configuration` to `coordinates` doesn't work, since of course coordinates don't have the `idx` attribute.
* Second problem: cell 8. Possibly related? But this seems to be choking inside of the visualization code.

Again, the rest of it runs without complaint.

**Comment by jhprinz** [comment]
`mem_test` should be easy to fix.

The visualization has a PR that is almost ready and should simplify the plotting a lot. I will fix the visualization after that To avoid changing it twice.

**Comment by dwhswenson** [comment]
> The visualization has a PR that is almost ready and should simplify the plotting a lot. I will fix the visualization after that To avoid changing it twice.

Make sense. Be sure to take a look at changes I made to it in #446, though -- that gives a recommended way of dealing with move schemes, networks, etc. (The move scheme ALWAYS contains the network, which ALWAYS contains the transitions. This is clearer than arbitrarily loading straight from storage.)

**Comment by jhprinz** [comment]
`tutorial_visualization` will be removed and replaced by specific ones for PathTreeBuilder and MoveTreeBuilder.

**Comment by dwhswenson** [comment]
@jhprinz : This was fixed in #397, right? (We *closed* #498 instead of merging it, so this didn't auto-close.) Can this be closed now?

**Comment by jhprinz** [comment]
Yes, this can be closed!
