### ISSUE TITLE
Speed up for MinusMove (FlatMinus)

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#463]
Not sure if that is feasible, just an idea. 

Working on the visualization for MoveTree lead me to a simple idea. It happened once in a while that in the minus we extend forward and then pick the first subtraj, which was the previously existing one. (Or the other way round, extend backward and pick the last subtraj) In that case the long minus simulation is (almost) not necessary and we could skip the long extension. This will reduce minus moves by a factor of two (obviously).

Currently we keep a minus sample around (type: 'A-X-A-----A-X-A') and we will always extend. If we would only keep a simple second `A-X-A` ensemble (Innermost ensembles) we switch (exchange) with, we could avoid the unnecessary long minus extension that does not go into generation of samples. 
(As explained above)

I see 2 potential problems:

1. There is a possibility that the extension will not be accepted and we skip that. I think that this will not be a real problem since (I think) detailed balance will still be preserved. At least I do not see, why

2. We will have less minus moves for statistics. But that might actually be an advantage since we can chose how much work we want to run getting the initial flux.

**Comment by dwhswenson** [comment]
This sounds like the SingleReplicaMinusMove. Already implemented. Has problems with MISTIS though. See #331.

**Comment by dwhswenson** [comment]
Oh, and looking back at it, I think my explanation on the SRMinus PR was pretty clear, so I'll point to that: #350. That's basically what you're suggesting, right?

**Comment by jhprinz** [comment]
Implemented as `SingleReplicaMinusMove`. Can be added as a strategy!
