### ISSUE TITLE
Conda problems?

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#487]
OPS doesn’t seem to be installing from conda. This has been a problem for a while (all the dynamiq-md packages have been failing for most of a month). I thought the problem might be specific to my setup in those Travis installs, and I didn’t have time to work on any dynamiq-md stuff until after I finished my Dutch course yesterday. But the master’s student I’m helping supervise was unable to install OPS, so it looks like a real problem.

It errors with:

```
Fetching package metadata: ........
Solving package specifications: .
Error:  Packages/dependencies missing in current linux-64 channels: 
  - dynamiq_samplers-dev 0.0.1 py27_0 -> openpathsampling-dev
  - openpathsampling-dev
```

This comes from https://travis-ci.org/dynamiq-md/dynamiq_samplers/builds/132439123.

Checking on https://conda.anaconda.org/omnia, I don’t see OPS under the “main” label. There is an old version under the “rc” label. However, even that version is way out of date: updated May 4; we’ve merged 9 PRs since then.

**Comment by jchodera** [comment]
Can you clarify what you are trying to install? openpathsampling (which is
built via the conda-recipes repo) or openpathsampling-dev (which is built
via your openpathsampling repo and should be printing out failure
information to your travis if it is failing to upload)?

**Comment by dwhswenson** [comment]
I'm trying to install the `-dev` -- but I'm confused on two points:

1. I thought (see #438; https://github.com/omnia-md/conda-dev-recipes/pull/29), that `-dev` was being built in `conda-dev-recipes`. We removed conda upload from our `.travis.yml` in #440. 
2. Why would there be a non `-dev` version? I thought we didn't have that yet, since we don't have a release or even a proper RC. 

I checked the [most recent nightly log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/127892758/log.txt) for the Linux build on `conda-dev-recipes`. It gives the following:

```
Uploading package '/anaconda/conda-bld/linux-64/openpathsampling-dev-0.0.0-py27_0.tar.bz2' to anaconda user 'omnia'...

Using Anaconda Cloud api site https://api.anaconda.org
detecting package type ...
conda
extracting package attributes for upload ...
done

Uploading file omnia/openpathsampling-dev/0.0.0/linux-64/openpathsampling-dev-0.0.0-py27_0.tar.bz2 ... 
[93m[WARNING] [0mDistribution linux-64/openpathsampling-dev-0.0.0-py27_0.tar.bz2 already exists ... removing

Upload(s) Complete

Package located at:
https://anaconda.org/omnia/openpathsampling-dev
```

Does the problem have something to do with labels? When I go to that URL, there's a message: "Warning: This package does not contain any files in the main label. Contact the package admin for developer install instructions."

**Comment by jchodera** [comment]
conda-dev-recipes builds have been disabled for weeks since a change to the
conda-build-all script broke this.  I will have to look into what is
required to revive this.
