### ISSUE TITLE
Reorganize `examples` directory

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#490]
As discussed a little in #482, we are all in agreement that the `examples` directory needs to be reorganized. Let’s figure out how to restructure it.

First point: does everyone agree with getting rid of the extra layer of `examples/ipython` and moving all the ipynb examples into the main `examples` directory? (All of our examples are ipynbs, the only other things in there will be initial information needed for startup, e.g., PDBs.)

Second: the structure within that directory. I gave a partial suggestion before, based on the idea that we would organize by system (toy, alanine dipeptide), then by method (TPS, TIS). @jchodera felt that it was better to organize by method, then by system.

I’ll put a proposal in the first comment below, and I’ll reserve this top post for description of the consensus.

## Consensus / Summary

* *do we move everything to `examples`?* (Agreed yes)
* *what overall structure do we decide on?* (Basically as below)

**Comment by dwhswenson** [comment]
What I’m suggesting now is a compromise between the method-first and system-first approaches. An important point is that there shouldn’t be too many examples that we distribute with the code: I’d like the web site to have links to lots of other examples (constantly growing as we develop new examples), but I think the core examples should be relatively few.

This means that we can use a combination of `system_method` as the directory names, and flatten the directory structure. So in that case, I suggest (and I *think* I included everything, but not entirely sure):

```
examples/
|- alanine_dipeptide_tps/
|- |- AD_flex_len_tps_setup.ipynb # alanine_dipeptide_tps_first_traj
|- |- AD_fixed_len_tps_setup.ipynb # alanine_dipeptide_fixed_tps_traj
|- |- AD_flex_len_tps_run.ipynb 
|- |- AD_fixed_len_tps_run.ipynb
|- |- AD_tps_analysis.ipynb
|- alanine_dipeptide_mstis/
|- |- AD_mstis_setup.ipynb
|- |- AD_mstis_prepare.ipynb
|- |- AD_mstis_restart.ipynb
|- |- AD_mstis_run.ipynb
|- |- AD_mstis_analysis.ipynb
|- |- AD_srtis_run.ipynb # still to come
|- |- AD_srtis_analysis.ipynb # still to come
|- simple_tps/
|- |- simple_fixed_length_tps.ipynb
|- |- simple_flexible_length_tps.ipynb
|- toy_model_mstis/
|- |- toy_mstis_setup.ipynb # currently “bootstrap”
|- |- toy_mstis_run.ipynb
|- |- toy_mstis_analysis.ipynb
|- |- toy_srtis_run.ipynb # still to come
|- |- toy_srtis_analysis.ipynb # still to come
|- toy_model_mistis/
|- |- toy_mistis_setup_run.ipynb
|- |- toy_mistis_analysis.ipynb
|- tests/
|- |- test_cv.ipynb
|- |- test_netcdfplus.ipynb
|- |- test_openmm_integration.ipynb
|- |- test_pyemma.ipynb
|- |- test_snapshot.ipynb
|- |- test_snapshot_modifer.ipynb
|- |- test_storageview.ipynb
|- |- storage_mem_test.ipynb
|- |- langevin_integrator_check.ipynb
|- misc/
|- |- committors.ipynb
|- |- fun_with_pathmovers.ipynb #?
|- |- sequential_ensembles.ipynb
|- |- tutorial_storage.ipynb
|- |- tutorial_visualization.ipynb
|- helper_files/ # better name for that?
|- |- toy_plot_helpers.py
|- |- AD_initial_frame.pdb #Alanine_solvated.pdb
|- |- debug_logging.conf
|- |- logging.conf
|- |- localtests.sh
```

**NOTE: All directories will have a `README.md` with a brief summary of the files contained.**

This means that `examples/README.md` reads something like this:

* `alanine_dipeptide_tps`: Transition path sampling (both fixed length and flexible length) on alanine dipeptide as a 2-state system. Compare with [Bolhuis, Dellago, Chandler PNAS 2000](http://dx.doi.org/10.1073/pnas.100127697).
* `alanine_dipeptide_mstis`: Multiple state transition interface sampling (including both multiple replica and single replica approaches) for alanine dipeptide as a 6-state system. Compare with [Du, Marino, Bolhuis JCP 2011](http://dx.doi.org/10.1063/1.3644344).
* `toy_model_mstis`: Multiple state transition interface sampling (including both multiple replica and single replica approaches) for a simple 3-state 2D model.
* `toy_model_mistis`: Multiple interface set transition interface sampling for a simple 3-state model.
* `tests`: Tests of various OpenPathSampling modules
* `misc`: Miscellaneous example code
* `helper_files`: Additional files used by the examples (initial PDB structures, logging configurations, etc)

Also, I think that most of the `test_*ipynb` notebooks that are run with Travis should be made into proper nose tests. Unit tests belong in `nose`, system tests can be variants on `examples`. Then there are tests that we can’t truly automate, because they are too stochastic to guarantee quick correctness results. For example, the `langevin_integrator_check` takes too long to be worth including in official tests, but needed to be run at some point to make sure that the integrator was giving reasonable distributions.

Move to `docs/`
```
move_strategies_and_schemes.ipynb
sliced_sequential_ensembles.ipynb #? really advanced topic; mainly docs on edge cases
troubleshooting_ops.ipynb
```

Not included above (remove?):
```
alanine.ipynb
alanine_dipeptide_old_example.ipynb
input.pdb
netinfo.dat
toy_bootstrapping.ipynb
toy_tis.ipynb
toy_analysis.ipynb
```

Features I like about this approach:
1. The names of the example notebooks are still unique, so if the user moves them, it is still clear what they were.
2. The names of the example notebooks are reasonably short (fit  2-wide in `ls` on an 80 character terminal)
3. Not too many things per directory (largest directory is `tests`, with 9 items (plus README) -- and some of those should move into being nose tests).
4. All examples that exist in sequences (with some notebooks depending on others) are in the same directory. This allows created files to be shared between examples.

**Comment by jhprinz** [comment]
Rename `helper_files` into `resources`

**Comment by dwhswenson** [comment]
@jchodera's comment from the other day

* add numbers to files in sequences so that they sort into the right order to run them

Anything else we talked about adding to this re-org that I left out? (Excluding things that are about adding things *inside* the examples, e.g., adding relevant links to docs -- those will come later)

Self-assigning this; I'll do it after we merge #386, #500, and #521 (all of which include new examples)

**Comment by jchodera** [comment]
From looking through the current examples, we need you guys to do the following:
* Organize examples into subdirectories with a few notebooks/subdirectory
* Rename the examples so they are sorted in the order they should be run
* Each directory should have a `README.md` briefly describing the example (and relevant reference, if applicable) and indexing the files 
* Ensure the current examples are being pulled into the online documentation are up to date
* The examples should give you a brief idea of the system you're working with early on. This could involve, for example, an illustration of the alanine dipeptide at the top and/or in the `README.md`, etc.
* Reduce the barriers to getting to illuminating examples about what you can do with the tool via http://openpathsampling.org so that it's easy for people to discover what they can do with the tool without a lot of reading.

This work might span multiple
