### ISSUE TITLE
Reorganize `analysis` directory

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#492]
The `analysis` directory not really all analysis any more. Some objects that were originally designed for after-simulation analysis also became simulation-setup tools (transitions, networks, move scheme).

This issue is mainly to suggest moving files around. I think it should look something like this:

```
openpathsampling/numerics/
|- histogram.py
|- lookup_function.py
|- wham.py
openpathsampling/analysis/
|- replica_networks.py
|- tools.py
|- single_trajectory_analysis.py
|- shooting_point_analysis.py
openpathsampling/???
|- networks.py
|- transitions.py
|- move_scheme.py
|- move_strategy.py
```

One somewhat significant change: splitting `tis_analysis.py` into `transitions.py` (which is mostly what it is) and `analysis/tools.py`.

As for the `???`, this could either be at the root `openpathsampling` layer, or in some subdirectory. I’d prefer a subdirectory, though I’m not sure the name for it. The point is that these modules provide very specific tools for TIS and TPS: they’re mainly relevant if you’re doing those types of path sampling. I think of them as sort of an `app` layer, so that might be a good directory name. I’m open to other suggestions.

There’s also a (seemingly very incomplete) `msm.py` that @jhprinz added there. Where would that belong?

Anyway, before doing this reorganization, I wanted to get feedback from others on what a better structure would be.

**Comment by jhprinz** [comment]
`msm.py` should be (when it is finished) either be in a separate folder or be separate from ops. For 1.0 this will be removed anyway so let's not worry about now.

About the `???` - we could place everything really TIS/TPS specific into a folder `sampling` or `tps` or something similar and all that is more general, like `networks.py` and `transitions.py` to the base level.

That way it will be easier to add msm and other sampling strategies later as well as to do the big split.

**Comment by dwhswenson** [comment]
> we could place everything really TIS/TPS specific into a folder `sampling` or `tps` or something similar and all that is more general, like `networks.py` and `transitions.py` to the base level.

Hmm. I think of `networks` and `transitions` as being the most TPS/TIS-specific aspects. I mean, the specific implementations are `TPSNetwork`, `MSTISNetwork`, etc.

The move schemes/strategies are *hypothetically* more broadly useful, but I don't think it's a good idea to try to use them too broadly.

The point of these was to provide a vastly simplified interface to path movers and ensembles. They're basically factories (and factories of factories) for ensembles/path movers. They create the other objects, and provide them with the context that is necessary for analysis.

I do *not* want to have to generalize any of these beyond the specific types of problems they're designed for. Ensembles are general. Networks and transitions are specific. Path movers are general. Move strategies and schemes are specific.

To the specific suggestions: I don't like either of `tps` (and have a separate `tis`? cluttered) or `sampling` (is it clear to a new user that these would be contained in there?) Maybe `path_sampling`, or `path_sampling_helpers` would be better?

Does the rest of the reorg make sense? (specifically, separate `numerics` directory -- personally, I'd like to separate those off in the big split, too: I like my histogram a lot more than numpy's, especially with the additional features I'll be adding soon.)

`msm.py`: shall I remove that, then? (as part of a PR doing this reorg, to be started once we know what to do about the `???` directory)

**Comment by dwhswenson** [comment]
In Skype call with @jhprinz : we think the `???` should be called `high_level`. This is only visible to developers; in the code these are still imported at the root `openpathsampling` namespace.
