### ISSUE TITLE
Add initial sampleset to MoveTree Visualization

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#494]
this will replace #453. We mainly agreed that the current visualization can be confusing because of the way we treat moves.

#### Example

A move will take a sample from ensemble `A` and create from it a sample in ensemble `X`. After that we will have a reversed move that will take the sample in `X` and create one in `A`. One would assume that the combined move should have input and output in `A`, but it will actually have input `A` and output `A` and `X`.

It gets even more complicated, if we have multiple samples per ensemble. Assume that initially there was something in `X` then the second move would chose between two and effectively depend on `X` so an input from `X` is necessary.

This is technically correct, but not what is really happening. Hence it is confusing to see and could alarm a user where everything is right.

One way to solve this is to add an initial sampleset or just a list of occupied ensembles before the mover is run. That should solve the ambiguity.

**Comment by dwhswenson** [comment]
Suggestion: make it possible to use the `MoveScheme` as the basis. If you use a `PathMover`, it assumes that *all* input ensembles are possible.

Taking just the initial sample set doesn't do it. Single replica: we want the possible moves for *all* possible initial samplesets, but only have *one* ensemble populated at a time.

If you allow `MoveScheme` as the input to MoveTree vis, it has a `list_initial_ensembles` method that will give you what you want.

Handle it as:

```python
try:
    # inp is a move scheme
    input_ensembles = inp.list_initial_ensembles()
except AttributeError:
    # inp is a path mover
    input_ensembles = inp.input_ensembles
```

If you want to visualize the move scheme with the appropriate context, you use the `MoveScheme` object.

**Comment by dwhswenson** [comment]
Oh, and add to that `mover = inp.root_mover` for the move scheme, and `mover = inp` for the path mover.

**Comment by jhprinz** [comment]
Good point. Working on this right now.
