### ISSUE TITLE
Include dummy moves in counting fraction of move attempts?

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#525]
A question, relevant for SRTIS:

***When counting the fraction of moves of a given type, should we include null (dummy) moves?***

*Context*: One check that the move scheme is behaving correctly is to examine the fraction of moves attempted with a given `PathMover`. So we figure out the number of moves for that mover, divide it by the total attempts, and compare the result to an expected number (for single replica, expected is calculated with the assumption of uniform sampling of the ensembles). We report this along with the acceptance ratio in the `scheme.move_summary` function. The question here is what should be the "total attempts": with or without dummy moves? SRTIS has dummy moves in order to satisfy detailed balance.

As an example, assume a simulation had 3 dummy moves, 2 shooting moves, and 1 replica exchange. Do we say that replica exchange was attempted 1/3 of the time, or 1/6 of the time?

*Advantage for not including the dummy move in the calculation (example answer is 1/3)*: Numbers should more closely match what we should get out of the multiple-replica scheme that the single replica scheme is based on.

*Advantage for including the dummy move in the calculation (example answer is 1/6)*: This normalizes based on the number of steps given to the `run` function. It’s also a more clear check of what the code actually does (includes the detailed balance corrections made by the dummy moves).

From a coding standpoint, including the dummy moves in the calculation may require modifying the `IdentityPathMover` to allow an option as to whether or not it should be included in this count. This is because it is used for both the initial conditions (which are never included in the count) and for these dummy moves, which would be included. I'd do this by adding an option `counts_as_attempt` to its `__init__`. Default would be not to include (`False`). I think that’s the easiest fix for it; probably only a few lines.

Thoughts? (I'd particularly like to hear from @bolhuis on this.)

**Comment by dwhswenson** [comment]
@bolhuis's suggestion was to not include the dummy moves, but to start the `move_summary` with a statement about dummy moves, if they are detected. It now looks like (e.g.):

```
>>> scheme.move_summary(storage.steps)
Null moves for 2224 cycles. Excluding null moves:
ms_outer_shooting ran 0.000% (expected 4.07%) of the cycles with acceptance 0/0 (nan%)
repex ran 25.316% (expected 36.59%) of the cycles with acceptance 8/60 (13.33%)
shooting ran 44.304% (expected 36.59%) of the cycles with acceptance 81/105 (77.14%)
minus ran 6.329% (expected 2.44%) of the cycles with acceptance 15/15 (100.00%)
pathreversal ran 24.051% (expected 20.33%) of the cycles with acceptance 56/57 (98.25%)
```

Current implementation also includes this when looking at a subset of moves. For example
```
>>> scheme.move_summary(storage.steps, 'minus')
Null moves for 2224 cycles. Excluding null moves:
SingleReplicaMinus ran 6.329% (expected 0.81%) of the cycles with acceptance 15/15 (100.00%)
SingleReplicaMinus ran 0.000% (expected 0.81%) of the cycles with acceptance 0/0 (nan%)
SingleReplicaMinus ran 0.000% (expected 0.81%) of the cycles with acceptance 0/0 (nan%)
```

This is because the percentages of cycles (both actual and expected) exclude the null moves. However, I can remove the null move warning line from the subset cases if you think that's better.

**Comment by jhprinz** [comment]
Hmmm, you might turn it into `logger.info` if that number is of no relevance. It might be good to look at it for certain cases though. Or you make a separate function that returns the value?

**Comment by dwhswenson** [comment]
In that example, I ran `2460` steps. 

Those `2460` steps consist of `0` MS outer shooting, `60` repex, `105` shooting, `15` minus, and `57` path reversal.

That doesn't add up to `2460`. I suspect the user might be confused.

This is only about a specific function which gives string output, so I don't think `logger.info` makes sense here. The whole point of this function is that you want to see some output. The question is what output is least confusing.

The percentage of cycles in this version should also line up with the percentages for the same network when doing multiple replica. That's the advantage to doing this. Also, you'd otherwise see something like `expected 0.002%` for each minus mover. All shooting together would be about `expected 0.035%`. In this, those percentages are the fraction of *non-dummy* moves.
