### ISSUE TITLE
[Q] Store used platform for OpenMMEngine ?

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#529]
### Problem

Currently we store the explicit platform used with the OpenMMEngine, so that we can later see that a snapshot was generated using `CUDA` or `CPU`. If you load an engine on a machine where the platform is not available you cannot continue a simulation though. This is in particular not useful, if you want to setup a system and save it and make it available for test cases. 

This is also a problem, if you store a `PathMover` where the engine was set explicitly. In that case you either have to recreate the PathMover using a scheme, but then you have all moves duplicated just to run with a different engine. It might also confuse analysis.

#### 1. Leave it

Keep it the way it is with benefits and problems it has. The pro is you really know, which snapshots are generated by CUDA and which ones using CPU

#### 2. Store only a default platform

Store a default platform or list of default platforms to be used. To override it you can pass an engine when `engine.initialize(platform=None)` is called. So you can flexible change the platform when you restart. 

Downside is that `engine` represents only openmm with a system but not the platform. You cannot infos which platform was actually used later!

I personally like 2. I can live with not knowning the platform. We can make it so that you can specify the list of platforms used in order by default, but this list is also the set of possible ones. 

###### Example

```py
engine = OpenMMEngine(topology, system, integrator, ['OpenCL', 'CPU'])
engine.initialize()  # will try to use OpenCL first and CPU as a fallback
engine.initialize('OpenCL')  # forces use of OpenCL
engine.initialize('CPU')  # forces use of CPU
engine.initialize('CUDA')  # not possible since not in initial list
```

#### Other ways

Use lots of utility functions to allow creating replacement engines, get these into PathMovers and fix analysis to handle multiple instances of pathmovers as one.

I can add this quickly to the alanine example PR.

**Comment by jchodera** [comment]
Why restrict the available platforms in the constructor, while also requiring a platform to be specified in initialize()? Is this to specify a fallback order in case the first platform is not specified?

Also, because you are using platform names and not Platform objects, this prevents you for specifying extra Platform parameters, like the precision model, which device to use, etc.

What about eliminating platform from the constructor, having intialize() try the default fastest openmm platform by default but optionally take a Platform object if a specific platform (and parameters) are desired (raising an exception if something goes wrong)?

We don't need to necessarily store which platform was used. It would be nice to have, but not necessary for a first release.

**Comment by jchodera** [comment]
Being able to control which device and precision model are used by specifying a Platform object is probably essential.

**Comment by jhprinz** [comment]
> Being able to control which device and precision model are used by specifying a Platform object is probably essential.

This is possible there is a special oom_options dict to be specified for these things

> Why restrict the available platforms in the constructor, while also requiring a platform to be specified in initialize()? Is this to specify a fallback order in case the first platform is not specified?

This was kind of the question, but I guess you answered it. If we do not need to know the specific platform that was used all this gets easy. I prefer not to use the built in picking, which fails on my machine. I have problems installing CUDA and OpenMM will pick this because it is installed but actually running a system fails because of a wrong Xcode version that is not compatible with the CUDA SKD. 

I would use a default order to try to get some idea of what we expect this to run on. Like never use `Reference`, but `['OpenCL', 'CPU']`.

I like the idea to just pass a platform object or a string to the initialize to override the default behaviour. Would that be okay?

**Comment by jchodera** [comment]
I feel strongly that we should let OpenMM pick the default fastest platform on its own unless the user specifies a specific Platform object to use. I don't think we should should mess with platform name string lists, specifying our own order of platforms, or anything else besides "let OpenMM pick" and "let the user specify the Platform object". All other options are either inflexible, unnecessary, or dangerous.

If OpenMM CUDA is not working on your machine and does not pick another platform by default, this is an openmm bug. Can you report this on the issue tracker?

In the meantime you should be able to work around this on your  machine by specifying an empty CUDA_VISIBLE_DEVICES, uninstalling CUDA, installing a working version, or specifying a specific Platform object, right?

**Comment by jhprinz** [comment]
Sure, will do...

**Comment by jhprinz** [comment]
Done. Now you cannot set a platform in the engine itself. You can only override initialization if you want to otherwise fastest will be used. I think I already posted the issue with CUDA and XCode. This does not seem to be a OpenMM problem

**Comment by jhprinz** [comment]
Just updation CUDA SDK to see if that works.

**Comment by jchodera** [comment]
Thanks!

OpenMM should at least fail gracefully if there is something wrong with your CUDA platform and switch o the next fastest platform. Did you mean that you already posted the issue to the OpenMM issue tracker? If so, can you send me the issue number?

**Comment by jhprinz** [comment]
Problem is that CUDA is listed, but it throws an error only when you start simulating and not before.
Cool, the latest CUDA update fixed it... CUDA is back!

**Comment by jchodera** [comment]
Great!

**Comment by jhprinz** [comment]
I think this has been solved for me. Updates will be in the alanine example PR
