### ISSUE TITLE
Cleaning up

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#532]
### Things to cleanup / not API related

- [x] remove subset from trajectories. This is not used and the API has changed a lot. I propose to replace this by a utility function that created a subset snapshot
- [x] remove/simplify `select_legal_sample` in PathMovers. This has also changed a lot and we do not need much of this
- [x] remove `clustering.py` this is very old and not maintained. It will reappear for MSMs but not in the current form
- [x] as discussed with @dwhswenson we should write a `test_tools_something` (put sane name here) that will provide all typically used testing helpers when running `from test_tools_something import *` (moved to #590)
- [x] fix scripts

**Comment by dwhswenson** [comment]
with #533 merged, I marked "remove `clustering.py`" as done

**Comment by jhprinz** [comment]
@dwhswenson  and me agreed to remove scripts for 1.0 and leave that as a feature for future updates. There are lots of examples to show how you can do the same and we have not used the scripts in months.
