### ISSUE TITLE
`engine.generate` as `iterator`

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#537]
##### Problem

This is related to cleaning up #521.

Another thing. I try to optimize the way to get the initial samples. I want to keep the simplest solution to be consistent with the other examples with is 

1. to get one single long trajectory that hits all states
2. use this to populate the initial sampleset

In the alanine example this can take a long time and I am impatient and want to see what the progress is. Really adding a progress reporting should be for later with the engine update `1.1`.

But I copied the generate function and made a little change and turned it in an iterator. This seems to be extremely cool and we should use this more, also for running PathSimulations...

##### Example

```py
# without iterator
trajectory = engine_high.generate(template, [hit_all_states])

# with iterator
it = engine_high.iter_generate(template, [hit_all_states], intervals=50)
for trajectory in it:
     print 'Currently the trajectory is of length %d' % len(trajectory)

print 'final trajectory is', trajectory 
# not that python 3 does not support leaking of local variables in loops so you need to
# define it first in the outer loop
```

I can't imagine a simpler way to do something like status report. 

I added another nice trick, that will capture a kernel interrupt and complete the engine step.
Return the current trajectory and then reraise the error. So you will not kill your engine or loose any simulation. You can even continue after a stop if you reuse the already existing trajectory. But that is for experimenting I guess.

The failing gracefully of engine steps I think is very important. When running in a notebook you don't want to interrupt your simulation at the wrong moment, like writing to disk!

**Comment by jhprinz** [comment]
I think #521 add this.

**Comment by dwhswenson** [comment]
Closing!
