### ISSUE TITLE
Document storage of positions / extracting Cartesian trajectories from storage?

### ISSUE THREAD

**Issue by jchodera** [openpathsampling/openpathsampling#560]
Looks like the [storage documentation](http://openpathsampling.org/latest/examples/storage.html) doesn't describe how atomic positions are stored, and how these can be extracted to provide actual trajectories or subtrajectories.

cc: https://github.com/choderalab/ligand-binding-pathsampling/pull/3#issuecomment-239504627

**Comment by dwhswenson** [comment]
@jchodera : Does http://openpathsampling.org/latest/topics/data_objects.html solve this?

**Comment by jchodera** [comment]
Yes, though the OPS 1 paper mentions the function `trajectory.md()` as a shorter way to do this than the docs (`openpathsampling.engines.openmm.tools.trajectory_to_mdtraj()`), so I'm confused about the discrepancy.

**Comment by jchodera** [comment]
Also, you might want to use the Sphinx cross-referencing syntax so that objects like `MCStep`, `Trajectory`, `Snapshot`, etc. are linked to their API docs:
http://www.sphinx-doc.org/en/stable/domains.html#cross-referencing

**Comment by dwhswenson** [comment]
> Yes, though the OPS 1 paper mentions the function `trajectory.md()` as a shorter way to do this than the docs

The paper is wrong on that... for some reason it is `snapshot.md` or `trajectory.to_mdtraj()`. These are equivalent to the `engine.openmm.tools.trajectory_to_mdtraj()` method (literally, one calls the other). I think the `trajectory.to_mdtraj()` version should be preferred. See #731.

I just updated the docs PR to reflect this: https://github.com/openpathsampling/openpathsampling/pull/744/commits/a96f18970db37a4d8caa332bf5d68482bd00a532

> Also, you might want to use the Sphinx cross-referencing syntax

Already doing so, but the cross-ref only works if the thing being referenced is in a toctree somewhere. This gets fixed for several of these objects in #744.

Sounds like everything is handled; closing this issue!

**Comment by jchodera** [comment]
> The paper is wrong on that... for some reason it is snapshot.md or trajectory.to_mdtraj(). These are equivalent to the engine.openmm.tools.trajectory_to_mdtraj() method (literally, one calls the other). I think the trajectory.to_mdtraj() version should be preferred. See #731.

Go ahead and fix it after merging https://github.com/choderalab/pathsampling-manuscripts/pull/58

Since that's wrong, I'm willing to be that there must be multiple additional errors as well. Can you review the code in detail to make sure it works?

> Already doing so, but the cross-ref only works if the thing being referenced is in a toctree somewhere. This gets fixed for several of these objects in #744.

Great! It's not too hard to reference these from the toctree to explain the major classes/objects. We do this in `openmmtools`:
http://openmmtools.readthedocs.io/en/latest/#modules
