### ISSUE TITLE
WESTPA package

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#565]
Does anyone know this? I guess it could be considered the most direct competitor, if so. But they have a framework to run Weighted Ensemble Simulations and analysis. Might be of interest.

https://westpa.github.io/westpa/

**Comment by dwhswenson** [comment]
Yes, I'm aware of them. I applied for a tenure track position at Pitt last year, would have been bad practice not to know of this! ;-)

**Comment by dwhswenson** [comment]
If you want to make a list of other packages doing similar things, you should add http://www.freshs.org/

**Comment by jhprinz** [comment]
I did not know. They recently published a paper about robust estimation of MFPTs and they compare to an MSM approach.

**Comment by jhprinz** [comment]
It might be good to just know what is out there. We definitely contribute something valuable, but it makes sense to know that people are using.

**Comment by jchodera** [comment]
It would be good to connect you guys up with @synaptocarbors (Josh Adelman)
who wrote much of the WESTPA code.

**Comment by jhprinz** [comment]
Sounds good. I think he left university recently, correct?
