### ISSUE TITLE
Remove unused/redundant code

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#566]
When reviewing the coverage I realized that we have some functions that are actually not used anymore or redundant. I think we should remove this to avoid confusion. I will start compiling a list of things I think we can safely remove and once we agree we can make a PR and remove the code. 

#### Where to use `#pragma: nocover
- [x] Check all the fail saves (e.g. `RuntimeError` as well)?
- [x] A function call like `if xyz is None: return None`?
- [x] Empty functions and abstract ones
- [x] Set operations that return `True` or `False`, e.g. `FullEnsemble.can_append ... return True`

#### Code to be removed

- [x] `Trajectory.n_frames` (we use `__len__`)
- [x] `Trajectory.prepend` (not used in regular python lists)
- [x] `Trajectory.n_atoms` use `traj[0].n_atoms`, `Trajectory.n_atoms` should return the number of atoms for each snapshot in the trajectory by passing to snapshot
- [x] `Trajectory.n_spatial` use `traj[0].n_spatial`, `Trajectory.n_spatial` should return the number of spatial dimensions for each snapshot in the trajectory by passing to snapshot
- [x] `SampleSet.__add__` I think we use `.apply_samples`
- [x] `Sample.__call__` returns the trajectory? Is there a reason for it
- [x] `NetCDFPlus.KeyDelegate` Not used anywhere.
- [x] `NetCDFPlus.clone_store` Not used anymore
- [x] `Storage.template`. `Storage.topology`, `Storage.n_atoms`, `Storage.n_spatial` since we can have mutiple snapshots this is not meaningful and can easily be replaced by `storage.snapshots[0].topology`, etc
- [x] `Ensemble._lencheck` Not used. Was originally to speed up testing for a trajectory being part of an ensemble by using length ranges.
- [x] `EnsembleCombination._continue_fnc` not used anymore
- [x] `Ensemble.use_shortcircuit` we strictly use `True` and so we could remove it
- [x] `SymmetricDifferenceEnsemble` and `RelativeComplementEnsemble`
- [x] `ChainDict.Transform` Not used anymore
- [x] `Topology.subset` We agreed to remove that
- [x] `SampleSet.__eq__` replace by `set(self.samples) == set(other.samples)`

#### Things to leave the way they are

- [x] `AppendedNameEnsemble` Is this still needed? Not sure.
- [x] `NetCDFPlus` option for variables `maskable` this previously was used to indicate that the entries in an array could be saved only partially. It used numpy.maskedarray to assign a spacial value to the meaning of masked (much like NaN) works. This is not needed anymore with the new CV implementation so we could remove or just leave it
- [x] `Ensemble.iter_extendable_slices` this was inspired by a discussion with John and David. It will give all (greedy _maximal_) subtrajectories that can be extended into the ensemble. Basically the ones that are one less frame than working subtrajectories with the exception that you do not need real subtrajectories. I would leave that. It might be useful at some point.
- [x] `Trajectory.n_snapshots` (we use `__len__`)

**Comment by dwhswenson** [comment]
(Not answering all tonight: it's midnight and I'm still at the office. But a first few.)

#### Where to use `#pragma: nocover`

In general: tests define the API. Thorough tests ensure that we don't break the API. So if the API includes giving a result (or error), there should be a test for it.

> Check all the fail saves (e.g. RuntimeError as well)?

If you can write a simple test for the error, then do so. If you can't think of a situation to test the error, then `no cover` it. But more often, you should be able to create the nonsense input that would cause the error (`if x < 0: do_first; elif x > 0: do_second; else: raise Error` -- just give `0` as input, even if that should never happen)

> A function call like if xyz is None: return None?

If you can write a simple test for that case......

> Empty functions and abstract ones

Again, usually easy to test, but I feel less strict about these. Especially if they raise `NotImplementedError`, because I think that's self-explanatory.

> Set operations that return `True` or `False`, e.g. `FullEnsemble.can_append ... return True`

Also feeling a bit more mixed on this one. Tests are easy, though. Probably better to do them than not.

#### Code to be removed

> `Trajectory.n_frames` (we use `__len__`)
> `Trajectory.n_snapshots` (we use `__len__`)

I'd say leave one of these. They're not unreasonable for someone to use. Might even just define it directly... `n_snapshots = __len__`, right? No extra function call? (We don't use `frames` elsewhere do we? We should make sure that all instances of `frames` is `snapshots`. At least, I think we standardized on that.)

> `Trajectory.prepend` (not used in regular python lists)

Hahaha! My only opposition to this is that no one will ever see the smart-ass comment I added next to it for posterity. ;-)


> `Trajectory.n_atoms use traj[0].n_atoms`, `Trajectory.n_atoms` should return the number of atoms for each snapshot in the trajectory by passing to snapshot
>  `Trajectory.n_spatial use traj[0].n_spatial`, `Trajectory.n_spatial` should return the number of spatial dimensions for each snapshot in the trajectory by passing to snapshot

I agree. We have a lot of changes to make in storage before we can do grand canonical, but why limit ourselves.

(More comments later... but I'm going home now.)

**Comment by dwhswenson** [comment]
(continuing from where I left off)

> `SampleSet.__add__` I think we use `.apply_samples`

I prefer `.apply_samples`. I think `__add__` is not as clear in usage.

> `Sample.__call__` returns the trajectory? Is there a reason for it

You tell me! You added it: https://github.com/openpathsampling/openpathsampling/pull/39/commits/ea049767bcdbe5f49421dabd3b43236f0b0bb1b7 :-)

I'm fine with removing that.

> `NetCDFPlus.KeyDelegate` Not used anywhere.
> `NetCDFPlus.clone_store` Not used anymore
>`NetCDFPlus` option for variables `maskable` this previously was used to indicate that the entries in an array could be saved only partially. It used numpy.maskedarray to assign a spacial value to the meaning of masked (much like NaN) works. This is not needed anymore with the new CV implementation so we could remove or just leave it
> `Storage.template`. `Storage.topology`, `Storage.n_atoms`, `Storage.n_spatial` since we can have mutiple snapshots this is not meaningful and can easily be replaced by `storage.snapshots[0].topology`, etc

Agree on all of these. If you don't think that `maskable` is likely to be used, then I'd say remove it.

> `Ensemble.iter_extendable_slices` this was inspired by a discussion with John and David. It will give all (greedy _maximal_) subtrajectories that can be extended into the ensemble. Basically the ones that are one less frame than working subtrajectories with the exception that you do not need real subtrajectories. I would leave that. It might be useful at some point.

I don't see this in master. Are you looking at an unmerged PR?

> `Ensemble._lencheck` Not used. Was originally to speed up testing for a trajectory being part of an ensemble by using length ranges.
> `EnsembleCombination._continue_fnc` not used anymore

Agree on both of these. And `._continue_fnc` is formally incorrect.

> `Ensemble.use_shortcircuit` we strictly use `True` and so we could remove it

Yep. I was going to suggest a `._debug_call`, etc for debugging purposes. But apparently I added all the relevant debug info in `_generalized_short_circuit`. Do keep all the debug information in there though! It has been helpful in the past.

> `SymmetricDifferenceEnsemble` and `RelativeComplementEnsemble`

Comment these out, but please leave the commented version in the code as a reminder to re-implement once we add the features of path ensemble theory.

> `AppendedNameEnsemble` Is this still needed? Not sure.

This was for the case that you had the equivalent ensembles in different replica exchange setups. Do we currently have the ability make a renamed copy of an ensemble? That's what this is needed for. See  https://gist.github.com/dwhswenson/c794e82745ca2b94c708

> `Topology.subset` We agreed to remove that
> `ChainDict.Transform` Not used anymore

These are good to remove.

#### Not used functions to be checked

> `SampleSet.__eq__` replace by `set(self.samples) == set(other.samples)`

Add the length check before that, and I agree. SampleSets can have duplicate samples if they haven't been reduced yet.

**Comment by jhprinz** [comment]
> I agree. We have a lot of changes to make in storage before we can do grand canonical, but why limit ourselves.

Haha, very nice. Although my comment just meant, that delegating from Trajectory to Snapshot means. That `Trajectory.n_atoms` will call `n_atoms` on all snapshots and return it. The only case I imagined was where we have a full and a reduced type snapshot and then you get a list of sizes...

**Comment by jhprinz** [comment]
Agreed on all points. No additional pragma: no cover... Closing
