### ISSUE TITLE
ImportError: No module named ipykernel.zmqshell

### ISSUE THREAD

**Issue by jchodera** [openpathsampling/openpathsampling#577]
Any idea what this could mean (after installing via `pip`)?
```
[chodera@gpu-1-17 cb7-b2]$ python setup-ops.py
Traceback (most recent call last):
  File "setup-ops.py", line 15, in <module>
    import openpathsampling as paths
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling/__init__.py", line 33, in <module>
    from analysis.move_scheme import (
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling/analysis/__init__.py", line 6, in <module>
    from tis_analysis import Transition, TISTransition
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling/analysis/tis_analysis.py", line 9, in <module>
    from openpathsampling.netcdfplus import StorableNamedObject
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling/netcdfplus/__init__.py", line 1, in <module>
    from netcdfplus import NetCDFPlus
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling/netcdfplus/netcdfplus.py", line 7, in <module>
    from dictify import StorableObjectJSON, UUIDObjectJSON
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling/netcdfplus/dictify.py", line 18, in <module>
    from openpathsampling.tools import word_wrap
  File "/cbio/jclab/home/chodera/miniconda/lib/python2.7/site-packages/openpathsampling/tools.py", line 7, in <module>
    import ipykernel.zmqshell
ImportError: No module named ipykernel.zmqshell
```

**Comment by jhprinz** [comment]
Yes, this is part of a little utility function that should check, if you run inside ipython, a notebook or plain python. It requires ipykernel to be installed. Not sure if there were recent changes in ipython.
It is not essential for OPS, it is only used to prevent terminal outputs when updating notebook outputs.

**Comment by jchodera** [comment]
Looks like it goes away if you install a recent `jupyter`, but it also prevented me from running anything until I did that.

**Comment by jchodera** [comment]
Perhaps you meant to install `jupyter` in the `requires` block of `setup.py`?
```
    'requires': [
        'python',
        'numpy',
        'scipy',
        'pandas',
        'netcdf4',
        'openmm',
        'openmmtools',
        'pymbar',
        'docopt',
        'pyyaml',
        'mdtraj',
        'svgwrite',
        'networkx',
        'matplotlib'],
```

**Comment by dwhswenson** [comment]
I think the better solution is to make it so that we have clean fallbacks if things that aren't *really* required aren't available, rather than adding them as requirements. @jhprinz: is this one easy to wrap in a `try: except ImportError:`? From your comment above, I assume that if `ipython` isn't available, then this particular thing should have no effect on how the code runs.

We have lots of other things like that still, especially in tests (e.g., pyEmma is not required to run OPS, but if you don't have it, the tests of pyEmma integration will fail). My opinion is that this should be ongoing cleanup past 1.0, but that we should clean these up if we come across them.

**Comment by jhprinz** [comment]
Yes, I should have caught the `ImportError` and if there is no IPython it just means console plain python...

**Comment by jhprinz** [comment]
#578 should fix this, too.

**Comment by dwhswenson** [comment]
Can we trust that #578 did, in fact, fix this? Looks like it to me; just want to know if I can close this issue.

**Comment by jhprinz** [comment]
I did not check again, but I added a try / catch to fix it.

**Comment by dwhswenson** [comment]
@jchodera : would the omnia conda build have caught further problems with this? 

@jhprinz : for that matter, now that you've made improvements on the test environment, do we run the base import (to check github version) outside the test environment? That would also be a check for this....

I think this can be closed, but we should check. Something as simple as writing out the git version on Travis while *not* in the test environment would definitely be a good test that everything we actually require is listed in our requirements.

**Comment by jchodera** [comment]
> @jchodera : would the omnia conda build have caught further problems with this?

The conda build *does* do `import openpathsampling` as a test. If that fails, the build will fail and we'd know about it. So I think so.

> I think this can be closed, but we should check.

I'll test 0.9.0 right now.

**Comment by jchodera** [comment]
I made sure to uninstall `jupyter` and `pyzmq` first, and after installing `openpathsampling` via `conda`, it seems to be working!

**Comment by dwhswenson** [comment]
@jchodera: Thanks! Sounds like time to close.
