### ISSUE TITLE
Add utility scripts

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#591]
These could be useful. Ideas are
1. netcdf+ viewer: Show the contents
2. storage conversion: Strip trajectories, remove snapshots, etc...
3. pathtree generator: To get a quick pdf to look at

**Comment by dwhswenson** [comment]
Closing this; we now have the OPS CLI (https://github.com/openpathsampling/openpathsampling-cli). Such scripts should be implemented as subcommands/plugins of the CLI. File contents viewer already implemented. I've done some work toward stripping snapshots. Path tree generator (and other analysis) may come later.
