### ISSUE TITLE
Potential bug in `testLeapfrogVerletIntegrator`

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#594]
I saw this error in the nosetest. Any idea? It happened after a rerun. So I think it is something statistically very unlikely ?

openpathsampling.tests.test_toy_dynamics.testLeapfrogVerletIntegrator.test_momentum_update ... Exception RuntimeError: 'maximum recursion depth exceeded' in <object repr() failed> ignored
Exception RuntimeError: 'maximum recursion depth exceeded' in <object repr() failed> ignored
Exception RuntimeError: 'maximum recursion depth exceeded' in <object repr() failed> ignored

**Comment by dwhswenson** [comment]
I saw this happen once too, but I have no idea what's going on. There's nothing recursive in this, nor is there anything stochastic. It just tests that the momentum update on a linear PES gives the correct value (which is pretty much trivial).

Was there no further traceback? It's hard to tell what's going on without that. I suppose I could add a bunch of debug statements, but I hate to do that deep in our integrator.

My best guess is that there is some weirdness in state for nose; maybe if the tests run in some particular order, some variable ends up getting redefined in some recursive fashion?

It's definitely not a bug in the integrator itself; it is probably a bug in the testing procedure.

**Comment by jhprinz** [comment]
Good enough for me. I have never seen it happen before. We are moving away from nose anyway so let's keep it for now. If someone has the same issue he will find this post.
