### ISSUE TITLE
OPS 0.9.1 release?

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#602]
OPS 0.9.0 has been out for 2.5 weeks -- shall we give a little bump to 0.9.1? 

I would like to do this after we merge #601 and #598. Each of those were put together for colleagues (the committor stuff related to a collaboration, and the docs for someone who will be helping us at the ESDW in November.) I'd prefer to send them emails saying that it is in the official code (after 0.9.1 gets into the omnia conda channel, at least)

@jhprinz : Do you have anything coming up in the next couple days that should be merged in before the next release? Any reason not to bump to 0.9.1 after those two merges?

Other things that would be included in this bump:

* switch JSON library to `ujson`
* lots of cleanup of examples (reorganization, correct state names in AD TPS)
* `masses`, `n_degrees_of_freedom`, and `instantaneous_temperature` snapshot features
* renamings surrounding what used to be `live_visualization` (see #596 for changes)
* end checking for "safe imports" in CVs (#599)
* lots of removals of unnecessary/outdated code
* temporarily pinned pyqt while we wait for a fix from conda (they thought they had one, but it didn't work for others)

**Comment by jchodera** [comment]
Sounds good.

I think you should use this opportunity to [bump the version number in `setup.py` now, though](https://github.com/openpathsampling/openpathsampling/blob/master/setup.py#L225).

**Comment by dwhswenson** [comment]
Thanks -- good point! Did it in #603. (Add another PR to the to-merge list before release!)

**Comment by jhprinz** [comment]
I have lots of little improvements for OPS that are relevant for running on a cluster, but we can move that to 0.9.2

This includes:
- better handling of ipython output conversion to regular print
- a jupyter conversion script to convert an ipython notebook into a stand-alone python script (this exists) with also converting headlines in markdown to print statements to track progress of the script.
- little convenience updates to the OpenMMEngine

**Comment by dwhswenson** [comment]
I'm hoping to get the release out no later than Wednesday (and ideally more like tonight or tomorrow). It sounds like the improvements you list above, as well as #574, aren't ready to be in a release right now, and so we'll add them in 0.9.2 (which will probably be in a week or two).

That would mean that the remaining things before a 0.9.1 release are #601, #603, and something that solves #605. Does that sound right to you?

**Comment by dwhswenson** [comment]
RELEASED! Availability through `conda` on the way: https://github.com/omnia-md/conda-recipes/pull/603
