### ISSUE TITLE
trajectory.to_mdtraj() not parsing box_vectors

### ISSUE THREAD

**Issue by sroet** [openpathsampling/openpathsampling#613]
While writing my own CV I noticed a difference between OPS wrapped code and pure mdtraj code. Namely the `trajectory.to_mdtraj()` doesn't includes the box vectors.
``` python
def mindist(snapshot, atom_list1, atom_list2):
    import mdtraj as md
    import itertools
    import numpy as np
    
    atom_pairs = list(itertools.product(atom_list1, atom_list2))
    #box_vectors = snapshot.box_vectors/snapshot.box_vectors.unit
    #unitcell_vectors = np.asarray([box_vectors])
    trajectory = paths.Trajectory([snapshot]).to_mdtraj()
    #trajectory.unitcell_vectors = unitcell_vectors
    all_distances = md.compute_distances(trajectory, atom_pairs=atom_pairs)
    mindist = min(all_distances[0])
    return mindist

my_cv = paths.FunctionCV("d_min_gly60_gly12", mindist, atom_list1=gln61, atom_list2=gly12)
```
![wrong](https://cloud.githubusercontent.com/assets/19587267/19235622/22a83a9a-8ef3-11e6-989f-dfd16a246b19.png)

When I uncomment the `box_vector` code above:
![right](https://cloud.githubusercontent.com/assets/19587267/19235635/325af392-8ef3-11e6-951a-513c9de6ecad.png)

**Comment by jhprinz** [comment]
Excellent catch. That should not be the case. I will make a quick PR to fix this. Thanks

**Comment by dwhswenson** [comment]
Already have it on the way, @jhprinz
