### ISSUE TITLE
Change in storing policy for referenced objects

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#620]
This is born out of convenience for restart and trying to reflect what a user might want to happen, when he saves an object.
#### The problem

Some objects, e.g. `Sample`, reference other "older" samples which are part of their history. This is useful to build path trees but when you save an object to a new storage the current _completeness_ policy will trigger storing all related samples, which will trigger storing all their related samples and so on. This will lead to completely re-save a full simulation and not just the single sample.

In this case what the user wants is to store only this last sample and not everything.
#### How to solve this

There are a few ways to get around this:
1. Make a copy of the objet that does not have the reference to the other objects. This is the simplest yet most technical solution. You need to know which objects can have this issue and need to decide where to make the _cuts_. For a sample this would be `.previous` but there could be more. So this requires a user to know about these problems and fix them manually.
2. There is a helper function for a sample set to do that for all samples alike. `sampleset.copy_without_parents()`
3. We change the policy on delegation of saving for some attributes. For samples this would mean that saving a sample the object referenced in `.previous` will be stored only with its UUID but the referenced object is not stored. This will cause what the _above_ user wanted. But it will not cause the chain of storing events which might have been expected. I could imagine some cases where it will not stuff but a user might think he had stored it. In the current setup I am pretty sure that we the exact behaviour we would like to have. But: If you then save a sample you need to save `sample.previous` by hand provided that it is not saved already (which it will be in the production case).

**Comment by sroet** [comment]
Would it be a possibility to define the storage behaviour of option 3 when opening a storage? 
For example if a storage is opened with ```fallback=True``` allow for another option like:
```
only_save_uuid_from_fallback=True/False
```

**Comment by jhprinz** [comment]
Yes, that would be possible and seems like a good idea. You can even change this behaviour on the fly since it does not affect the storage itself, only what is stored. 

If I understand you you want to exclude things that are not yet stored in the fallback storage, i.e. only store, if you cannot load the object in any way. That seems like a good default, when you have a fallback attached, just use it. In case you do want our current behaviour there could be an option to really store everything despite it being already in the fallback.

I would say we we do not need option 3. then and the fallback based is much simpler and cleaner for the user. Thanks.

**Comment by sroet** [comment]
> If I understand you you want to exclude things that are not yet stored in the fallback storage, i.e. only store, if you cannot load the object in any way. 

Yes this is indeed what I would like to use.

**Comment by jhprinz** [comment]
Is this solved now?

**Comment by dwhswenson** [comment]
This was supposedly solved by #636, so I think it can be closed.
