### ISSUE TITLE
Release 0.9.2

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#642]
It's been nearly 2 months, 167 commits to master, and 25 PRs merged since we released 0.9.1. In addition, we've made changes that affect the OPSPiggybacker (which runs tests based on the most recent OPS release, which is now incompatible with my local version; main problems are from #633, plus a little from #616). Shall we do a new release?

**Comment by jchodera** [comment]
I'd recommend weekly or biweekly bugfix (0.9.x) releases until the 1.0.0 release.

**Comment by jhprinz** [comment]
Definitely, @dwhswenson can you cut the release? Do you have all the necessary information on changes?

**Comment by dwhswenson** [comment]
@jhprinz : Sure, I think I have everything (easy enough to sort PRs by last-updated). Might not get to it until later tonight or tomorrow, but unless you have something you're planning to merge soon, I think we're due for a release.

@jchodera : I don't think we'll need weekly releases, and might not even need biweekly. We haven't merged anything in a week. I have a few small features still to add, but most of what I see left is more tests and more docs, neither of which really matter for a release (the docs are already on the website once they're merged to master; the tests just ensure that the code stays sane). At this point, we're very near a release candidate -- At this point, there may be more hours of work to be spent on the paper than on the code.

**Comment by dwhswenson** [comment]
(clarification to above: we might do biweekly checks of "should we cut a release?", but I doubt we'll actually cut a release every time we look at it.)

**Comment by jhprinz** [comment]
Let's aim the next before Christmas.

**Comment by dwhswenson** [comment]
Agreed -- by Christmas I hope to have added a few small features (ways of modifying the shooting point for 2-way shooting), which can certainly be part of a new release. Between now and when I leave for the holidays (Dec 20), most of my OPS work is on turning things into official E-CAM modules, although there may be little pieces of cleanup I do.

**Comment by jhprinz** [comment]
Yes, I had some speedup and simplification of the storage that I needed for the cluster, etc. It is backwards compatible. it also removed the non used `non-uuid` mode, adds better splitting, etc...

**Comment by dwhswenson** [comment]
Released!
