### ISSUE TITLE
`storage.tag` or `storage.tags`?

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#643]
I think the subject says it all. Almost all of our stores are plural. However, it is `storage.tag`, not `storage.tags`.

My suggestion: make one an alias of the other, so that both work and refer to the same object.

(I bring it up because I keep typing `storage.tags['name'] = object`, getting an error, and having to correct it.)

**Comment by jhprinz** [comment]
I have the same problem :) So let's change that. For backwards compatibility let's keep both. Btw. We could have an `AliasStore` which is stored itself so a user could (not sure if that is recommended) add aliases. E.g. `storage.frames -> storage.snapshots`.

For now just add in the `__init__` at some point : `self.tags = self.tag`

**Comment by dwhswenson** [comment]
> I have the same problem

Glad I'm not just crazy! :-)

> We could have an AliasStore which is stored itself so a user could (not sure if that is recommended) add aliases.

I think that might be overly complicated, especially because it would mean that one research group's standard terminology when working with OPS might differ from another, making it hard for the community to help each other.

I think the simple alias for this case is the best idea.

**Comment by jhprinz** [comment]
Agreed. I originally wanted a really short word to, well, keep it short. We might just use `storage['name'] = ...` instead of `storage.tags['name']`, but I need to make sure that does not comflict with the netcdf API.

So let's just add this one line for now.

**Comment by jhprinz** [comment]
I can put this in as part of #662 or we do a separate one. The change is simple but need to update some examples as well.

**Comment by dwhswenson** [comment]
Make it a separate PR, please.

Also, for the time being, can we have support for both words? This is already in use. We can deprecate it for 2.0, and update the examples to provide the preferred version, but we should stay backward-compatible. (Easy enough to have `.tag` map directly to `.tags`)
