### ISSUE TITLE
Unpin numpy 1.10 (waiting on upstream)

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#656]
Incompatibility with netcdf4 and hdf4 were temporarily fixed in #655 by pinning numpy to 1.10.

Watching https://github.com/ContinuumIO/anaconda-issues/issues/1360 for a solution to the problem, at which time we can unpin.

**Comment by jhprinz** [comment]
Any news here?

**Comment by jhprinz** [comment]
Works now without pinning, but it still uses numpy 1.10. Resolved by PR #677 .
