### ISSUE TITLE
pyretis

### ISSUE THREAD

**Issue by jchodera** [openpathsampling/openpathsampling#661]
Have you guys seen [pyretis](http://www.pyretis.org/)?

**Comment by dwhswenson** [comment]
Yes. One of the authors is visiting our group in Amsterdam. He and I have been discussing ways that our codes can benefit from each other.

**Comment by jhprinz** [comment]
Yes, I had the two developers coming two Berlin in 2015 already. Very nice guys and great project, we had some joint things planned for the future, but decided at the time that the two codes have a different focus and we could try to use the same analysis, i.e. write an import for their result to our anaysis and see if we get similar results.

**Comment by dwhswenson** [comment]
Start to code for converters between PyRETIS and OPS: https://github.com/op-yreti-s/gutis (One of the results of me spending the last 1.5 weeks in Trondheim.) Both the PyRETIS devs will be at the ESDW in Leiden.

Closing this issue, since I don't think there's anything else to do about it!
