### ISSUE TITLE
Update default colors of move decision tree visualization

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#682]
The move decision tree visualization encodes really useful information about input and output ensembles. However, the default color scheme (using green tops for input, red bottoms for output, and grey box) is very hard to distinguish from the color of the box for people with certain kinds of colorblindness (specifically, the ~1% of the population with either protanopia or deuteranopia.)

Here's what an output from this visualization looks like, next to a simulation of what it looks like to someone with deuteranopia (protanopia is similar):

![movetree_colorblind](https://cloud.githubusercontent.com/assets/8178546/25071317/292184e4-22b4-11e7-95c6-8d63460c726c.png)

With careful attention, a colorblind user will see the tops and bottoms, but I think that adjusting the color scheme (perhaps adjusting the color of the main box? putting some shape to the input-output bars?) will make it easier. It seems especially hard to distinguish the bottoms from the box.

**Comment by jhprinz** [comment]
This has been changed to red and blue. Do we want to close this? We should think about the path tree as well.

**Comment by dwhswenson** [comment]
> This has been changed to red and blue. Do we want to close this?

Yes, I think that whichever PR included those changes should have closed this. Closing.

> We should think about the path tree as well.

Agreed. We should get some input from @bolhuis on that as well, since I think he's the one who initially set up the path tree picture with red/green paths. My vote is to replace the default green with a default blue, which avoids problems for the most common kind of colorblindness. (And the beauty of @jhprinz's setup in this is that you can create any color scheme you want with just a little CSS, so users can customize as they wish.)
