### ISSUE TITLE
compatible to Python 3

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#70]
Coule we change the code so that it runs also under Python 3?
I had the idea to add a Siegtank converter which would allow to import a complete Siegetank project into our netCDF Storage and continuously sync it, as it progresses.
The idea was to just get the actual status of a siegetank project. Get all the trajectories one by one, strip water and store the essential part (I assume that I don't need water and or momenta) in our storage.
Unfortunately Siegetank requires Python 3 and to avoid having to seperate scripts it would be great to keep out code also runnable (if not optimal) under Python 3. 

This seems to involve mainly
- change `print` to `print()`
- take care of unicode strings
- rewrite some iterables (e.g. iterates() does not work in Python 3)

which is not too much work. Most of it can be done automatically.

Would that be a good goal? I mean importing from Siegetank is a nice gimmick but potentially not relevent unless we want to use Siegetank at some point to run our trajectories (which would be compatible withe the next simulation generator scheme)

**Comment by jhprinz** [comment]
I just saw that my idea has a compatibility check mode and it will highlight all parts that are not 2.7 and 3.5. I will have a look at how complicated that is...

**Comment by dwhswenson** [comment]
This has been superseded by #714. Closing with the intent of keeping further developments there.
