### ISSUE TITLE
.md attribute does not pass unitcell information

### ISSUE THREAD

**Issue by sroet** [openpathsampling/openpathsampling#710]
I expected the following code to do the same thing, but `.md` does not parse the unitcell information. Is this the intended behaviour?
```python
import openpathsampling as paths
import openpathsampling.engines.openmm as peng_omm

# Use the examples pdb
ops_dir = paths.__file__.rsplit('/',2)[0]
snap = peng_omm.snapshot_from_pdb(ops_dir+"/examples/resources/AD_initial_frame.pdb")
traj = paths.Trajectory([snap])

print traj[0].md
print traj.to_mdtraj()[0]
```
returns
```
<mdtraj.Trajectory with 1 frames, 1651 atoms, 546 residues, without unitcells>
<mdtraj.Trajectory with 1 frames, 1651 atoms, 546 residues, and unitcells>
```

**Comment by jhprinz** [comment]
No, I don't think so, but right now I have to guess. I think we export purely coordinates, which leads to this. I think we need to fix this, whereas for most mdtraj features this is not problematic there could be some there it is. I will issue a PR to fix this.

**Comment by dwhswenson** [comment]
Should there even be a `.md`? It's already sort of deprecated. At the least, convert it to just doing `return paths.engines.openmm.tools.trajectory_to_mdtraj(self)`.

I think that having MDTraj conversions in places that aren't OpenMM-specific may be dangerous. It looks to me like there are a lot of assumptions that we're using OpenMM in these parts of the code.

**Comment by jhprinz** [comment]
Not sure, what you mean with OpenMM specific? This is part of the openmm.snapshot? So, if we have that, then I agree, we should reuse `...trajectory_to_mdtraj(Trajectory([self]))` or something like this...

**Comment by jhprinz** [comment]
Was looking at it. Pretty cool actually. This is part of the statics feature and then makes it into the snapshot... Cool...

**Comment by jhprinz** [comment]
While at this. There is also a `Trajectory.to_mdtraj` which is equally openmm specific. We even have notes about this in the code...

**Comment by dwhswenson** [comment]
Right now, the actual code is in `Trajectory.to_mdtraj`. The `...trajectory_to_mdtraj` just calls it, but yeah, the idea was to switch the location eventually. I think `...trajectory_to_mdtraj` is the one that will survive, so if we keep `.md` in, it should reuse the code from there.

> Was looking at it. Pretty cool actually. This is part of the statics feature and then makes it into the snapshot... Cool...

Downside is that it makes it hard to find the code! Took me a while to find where it was.

In principle, some code might use `statics` but not be able to interface with MDTraj (can LAMMPS convert to MDTraj?) That's the reason not to have it in there; maybe make it a separate feature in `engines/openmm/features/`?

**Comment by dwhswenson** [comment]
> I think that having MDTraj conversions in places that aren't OpenMM-specific may be dangerous.

I'm going to contradict myself on this. Looking at it more, the only thing that is needed for an engine to have MDTraj support is that it needs to have a way to get an MDTraj topology.

Putting the conversion in the `Trajectory` object or in a separate function are both reasonable, but it isn't OpenMM-specific. If you can generate an MDTraj topology from a LAMMPS engine (or Gromacs, where it should be easy), then you should have everything you need to do all the MDTraj-based stuff you might want.

Engines that don't have it should fail with a reasonable error (`AttributeError` is accurate, and what would happen by default). I set this up in #731.
