### ISSUE TITLE
Update (fix deployment) of online documentation

### ISSUE THREAD

**Issue by jhprinz** [openpathsampling/openpathsampling#711]
This has 2016 in the bottom. I guess it is not up-to-date.

**Comment by dwhswenson** [comment]
The copyright notice is just a string in the `conf.py` -- I'll update that, but it isn't indicative of the uploading of docs.

However, there *is* a problem with uploading docs. I'll try to fix that as well. (Unless you're already working on it, @jhprinz -- but I'm pretty sure I know how to fix it, and it won't take long.)
