### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#714]
Converting #689 to an issue, so we can close that PR and instead do it in several smaller PRs. This covers the process of updating OPS to work with Python 3. See also #70.

Big picture tasks:

- [x] Update Travis script to test 2.7, 3.5, 3.6
- [x] Fix nosetests to work with 2.7, 3.5, 3.6
- [x] Fix notebook tests to work with 2.7, 3.5, 3.6
- [ ] Check that all untested notebooks work in 3.6 as well
- [ ] Clean up automated additions in testing (zip, range, old_div; some changes not needed)

---

Notebooks, divided by directory. An asterisk after the notebook name indicates that it is part of the standard test suite.

**`examples/tests/`**
- [x] `langevin_integrator_check.ipynb`
- [ ] `storage_mem_test.ipynb`
- [x] `test_cv.ipynb`*
- [x] `test_netcdfplus.ipynb`*
- [x] `test_openmm_integration.ipynb`*
- [x] `test_pyemma.ipynb`*
- [x] `test_snapshot.ipynb`*
- [x] `test_snapshot_modifier.ipynb`
- [x] ~~~`test_storageview.ipynb`~~~

**`examples/toy_model_mstis/`**

- [x] `toy_mstis_1_setup.ipynb`*
- [x] `toy_mstis_2_run.ipynb`*
- [x] `toy_mstis_3_analysis.ipynb`*
- [x] `toy_mstis_4_repex_analysis.ipynb`*
- [ ] `toy_mstis_5_srtis.ipynb`
- [ ] `toy_mstis_A1_split.ipynb`
- [ ] `toy_mstis_A2_split_analysis.ipynb`

**`examples/toy_model_mistis/`**
- [x] `toy_mistis_1_setup_run.ipynb`*
- [ ] `toy_mistis_2_flux.ipynb`
- [x] `toy_mistis_3_analysis.ipynb`*

**`examples/misc/`**
- [ ] `committors.ipynb`
- [ ] `custom_strategy_repex_shoot_repex.ipynb`
- [ ] `fun_with_pathmovers.ipynb`
- [ ] `move_strategies_and_schemes.ipynb`
- [ ] `tutorial_handle_nan.ipynb`
- [ ] `tutorial_movetree_visualization.ipynb`
- [x] `tutorial_path_histogram.ipynb`
- [ ] `tutorial_pathtree_visualization.ipynb`
- [x] `tutorial_storage.ipynb`*

**`examples/simple_tps/`**
- [ ] `simple_fixed_length_tps.ipynb`
- [ ] `simple_tps.ipynb`

**`examples/alanine_dipeptide_tps/`**
- [ ] `AD_tps_1_trajectory.ipynb`

(If the first AD TPS notebook works, I'll assume that the remaining AD TPS and MSTIS notebooks also work. They take too long to run to actually test them all.)

**Comment by jhprinz** [comment]
I think `test_storageview.ipynb` can be removed. We do not have a function `StorageView` anymore. This was removed in favor of using steps in functions anyway.

**Comment by dwhswenson** [comment]
This is *long* since resolved (now we **only** support Python 3!) Closing.
