### ISSUE TITLE
Some Storage properties break when changing working directory

### ISSUE THREAD

**Issue by hejung** [openpathsampling/openpathsampling#774]
The following example code produces an error at the second print statement:
```python
import openpathsampling as paths
import os

storage = paths.Storage('test.nc', 'w')
os.chdir('..')
print(storage.filename, storage.filepath())
print(storage.file_size)
```
Error: 
```
test.nc test.nc

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-37-628e081a85fb> in <module>()
      5 os.chdir('..')
      6 print(storage.filename, storage.filepath())
----> 7 print(storage.file_size)

~/Documents/Master/OPS/openpathsampling/openpathsampling/netcdfplus/netcdfplus.py in file_size(self)
    355     @property
    356     def file_size(self):
--> 357         return os.path.getsize(self.filename)
    358 
    359     @property

~/conda-envs/NNOPS/lib/python3.6/genericpath.py in getsize(filename)
     48 def getsize(filename):
     49     """Return the size of a file, reported by os.stat()."""
---> 50     return os.stat(filename).st_size
     51 
     52 

FileNotFoundError: [Errno 2] No such file or directory: 'test.nc'
```

I think the reason is that `storage.filename` returns a relative path, as does the netCDF function `storage.file_path()`.
Could it be a solution to use `self.filename = os.path.abspath(filename)` in https://github.com/openpathsampling/openpathsampling/blob/692ee2c88beb5d38b69fac6c6ac97ed8610aff08/openpathsampling/netcdfplus/netcdfplus.py#L237 ?
Or maybe add an `self.abspath = os.path.abspath(filename)` ?

**Comment by dwhswenson** [comment]
Yes, `storage.filename` is exactly what is given as input, so if you `chdir` and then call a function that actually requires the file path, it would raise an error. 

@jhprinz: does it make more sense to add an implicit storage of the `cwd` when opening the storage (and to use that in and function that uses `self.filename`) or to modify `filename` to be an absolute path? Those seem to be the obvious options.

**Comment by jhprinz** [comment]
I think we should turn filename into a readonly property and convert the filename into an absolute path. That sounds reasonable. Make sure that you can give file paths absolute and relative and that the path is always converted, but that should be trivial.
