### ISSUE TITLE
Pandas 0.23 raises FutureWarning about as_matrix()

### ISSUE THREAD

**Issue by sroet** [openpathsampling/openpathsampling#775]
Since Pandas version `0.23` the tests start raising `FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.` 
It is mostly used inside the tests, but also in `openpathsampling/openpathsampling/numerics/wham.py`. This could result in this warning popping up for users when doing analysis.

**Comment by jhprinz** [comment]
@sroet I made a PR to resolve this and indeed replaced `.as_matrix()` with `.values` Note, that `.values` is not a function anymore. See #781
