### ISSUE TITLE
openMM engine does not accept: n_frames_max=None

### ISSUE THREAD

**Issue by hejung** [openpathsampling/openpathsampling#817]
The docs say int or None is an accepted value but setting None I get a ValueError. Setting to integer values works.
I think the problem is the combination of the default value beeing an int for the openMM engine and the basic dynamics engine checking that the types of variables match the default type in `openpathsampling.engines.dynamic_engine._check_options()`.

**Comment by dwhswenson** [comment]
I think we'll take the code over the docs on this one. `None` is a rather strange value for it, anyway. I think there should always be a maximum number of frames as a precaution (make that value very high if you trust that you won't get stuck somewhere else!)
