### ISSUE TITLE
TIS issue : Initial trajectory not satisfying the ensembles (although it crosses all interface)

### ISSUE THREAD

**Issue by arjunwadhawan** [openpathsampling/openpathsampling#837]
Hi,

I am trying to run a RETIS simulation using OPS (0.9.6). I have an initial trajectory that starts in state A, crosses the interfaces and goes to stateB. It somehow does not accepts the initial trajectory. It could be that the way I described my network(maybe) is not right. Would be glad if someone can help 
 
Summary : 
State A : Order parameter (OP) = 2
State B : OP =25
Initial Trajectory goes from OP = 2 to OP = 42 
Interfaces placed at OP = 5,6,7

Following is the setup

To run the simulation , type `./retis.py*`

I get the following error in the log file 

```
Missing ensembles:
*  [liquid->crystal 0]
*  [liquid->crystal 1]
*  [liquid->crystal 2]
*  [liquid MIS minus]
No extra ensembles.
Traceback (most recent call last):
  File "./custom_retis.py", line 210, in <module>
    gausian_simulation = paths.PathSampling(storage, scheme, initial_conditions)
  File "/home/aarjun1/miniconda2/envs/16_05_2019/lib/python2.7/site-packages/openpathsampling/pathsimulators/path_sampling.py", line 76, in __init__
    template_trajectory = self.sample_set.samples[0].trajectory
IndexError: list index out of range
```

**Comment by dwhswenson** [comment]
OPS volume definitions no longer include their upper bounds (see #772). Therefore, your state definition for the liquid is `1 <= MCG < 2`, but the minimum value in your trajectory is 2. So it never visits the liquid state. Change the upper bound to, e.g., 2.1, and it will work.

Note that you'll still need to add a trajectory for the minus ensemble. The easiest way to do that is to just run straight MD until you have a trajectory that satisfies the minus ensemble.

***

Quick explanation of how to diagnose this, so this can be useful to anyone who finds it later:

1. A fast way to diagnose this specific problem: `TISEnsemble`s have an extra method called `trajectory_summary`. Running `network.sampling_ensembles[0].trajectory_summary(trajectory)` gives a dict, telling us that the initial state is `None` and the minimum value of the CV is 2. That would make it quick to diagnose.

2. How I really diagnosed this one: First, plot the trajectory as a function of the CV (here called `MCG` using `plt.plot(MCG(trajectory))`. This often tells you if anything is weird. Second, print out the description of a sampling ensemble with `print(network.sampling_ensembles[0])`. Those mathematical descriptions can require some attention to read and understand, but it provides a mathematical description of what the ensemble actually implements (and exist for ALL ensembles, not just `TISEnsemble`s). From there, look for something weird. This part popped out pretty quickly as suspicious, and `min(MCG(trajectory))` confirmed that the minimum value was 2, which is the same as the (excluded) upper bound in the state definition.

**Comment by arjunwadhawan** [comment]
Hey David,

Thanks, Indeed I was using OPS 0.9.3 till now. The volumes bounds now make sense.
Also, my simulation was crashing before (as I had no trajectory for minus ensemble). Your answer helped me exactly where I was stuck 

Arjun
