### ISSUE TITLE
ImportError: cannot import name RestorableIntegrator (when accessing snapshots)

### ISSUE THREAD

**Issue by arjunwadhawan** [openpathsampling/openpathsampling#852]
Hi,

I am trying to load in a old storage generated with old OPS version and run a Path sampling with it in new OPS version 
**New version :** 
openmm                    7.4.0           py27_cuda101_rc_1    omnia
openmmtools               0.6.2                    pypi_0    pypi
openpathsampling          1.0                      py27_0    omnia

**Old Version**
openmm                    7.3.1           py27_cuda92_rc_2    omnia
openmmtools               0.16.0                   py27_0    omnia
openpathsampling          0.9.6                    py27_0    omni

I cannot access the snapsohot. In particular, following line fails 
`template = old_storage.snapshots[0]` 

`ImportError: cannot import name RestorableIntegrator`
Attached is the full error. What could be a way around this ? I think I have seen this before but cant recall the issue again. 

Let me know if more information is needed 

<img width="1891" alt="Screenshot 2019-09-17 at 13 48 40" src="https://user-images.githubusercontent.com/21062948/65039160-e3dcfd80-d951-11e9-8121-093ff3f6bcf7.png">

**Comment by dwhswenson** [comment]
This is related to #764. You need to upgrade `openmmtools` from 0.6.2 to 0.15 or greater (0.16 is the last Py2 version). I have no idea why your install got such an old version of `openmmtools`!

**Comment by dwhswenson** [comment]
> openmmtools 0.6.2 pypi_0 pypi

Also, I'm not sure how you got `openmmtools` from `pypi` ... I don't see it listed on pypi

**Comment by arjunwadhawan** [comment]
Updating `openmmtools ` solved the issue. Thanks 
Hmm.. truw, don't know how pypi is involved. Will check
