### ISSUE TITLE
NetCDF error when loading in a storage of a running simulation

### ISSUE THREAD

**Issue by arjunwadhawan** [openpathsampling/openpathsampling#858]
Hi. I am running one of the latest version (7.4.0) of OPS and my simulation generates storage files (.nc) which I need to analyse while simulation is running 

Whenever I do this, I get the following error .
An easy work around is I copy the storage to another file. Then it is not actively being used in OPS and hence it works but sometimes my storage goes upto terra -bites and doing this becomes impossible. 

What would be the right way to fix this  
<img width="1099" alt="Screenshot 2019-09-26 at 12 11 20" src="https://user-images.githubusercontent.com/21062948/65680194-c6e1b200-e056-11e9-85b0-7e6887195a85.png">

<img width="1248" alt="Screenshot 2019-09-26 at 12 10 40" src="https://user-images.githubusercontent.com/21062948/65680144-b3cee200-e056-11e9-952b-a2beaa51821b.png">

**Comment by dwhswenson** [comment]
This has been a problem for a while. Something changed under the hood of netcdf. @jhprinz : Any chance you can look at this?

**Comment by IdsTeepe** [comment]
So I found out what is the underlying issue:
`openpathsampling` uses `netCDF4`, which in turn uses `h5py` to read the storage. 
Since `h5py` 1.10.0, it now tries to lock the file by default, regardless of using read-only mode or not.
The simple fix: set the environment variable `HDF5_USE_FILE_LOCKING` to `FALSE`

The output of the following snippet (after loading the storage with another process) is self-explanatory:
```
import openpathsampling, netCDF4, h5py, os

storagepath = 'ca_7_13_test.nc'
try: storage_h5py = h5py.File(storagepath, 'r')
except OSError as e: print(f'h5py:    {e}')
try: storage_netCDF4 = netCDF4.Dataset(storagepath, 'r')
except OSError as e: print(f'netCDF4: {e}')
try: storage_paths = openpathsampling.Storage(storagepath, mode='r')
except OSError as e: print(f'OPS:     {e}')

os.environ["HDF5_USE_FILE_LOCKING"]="FALSE"
storage_h5py = h5py.File(storagepath, 'r')
print(type(storage_h5py))
storage_h5py.close()
storage_netCDF4 = netCDF4.Dataset(storagepath, 'r')
storage_paths = openpathsampling.Storage(storagepath, mode='r')
for storage in [storage_netCDF4, storage_paths]:
    print(type(storage))
    storage.close()

--------Output--------
h5py:    Unable to open file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
netCDF4: [Errno -101] NetCDF: HDF error: b'ca_7_13_test.nc'
OPS:     [Errno -101] NetCDF: HDF error: b'ca_7_13_test.nc'
<class 'h5py._hl.files.File'>
<class 'netCDF4._netCDF4.Dataset'>
<class 'openpathsampling.storage.storage.Storage'>
```
Of course, I didn't find this environment variable myself; credit goes to [Florian](https://stackoverflow.com/users/1697676/florian) in [this answer](https://stackoverflow.com/a/49317928).

**Comment by dwhswenson** [comment]
@IdsTeepe : Thanks for tracking down a solution! This has been in the pile of "yes, I know it is a problem, but other things are higher priority" for a while now. Your help is much appreciated.

@arjunwadhawan : Does this solve for you? Can the issue be closed?

Just to be clear to anyone else who has this problem: It appears that the solution is to set the environment variable `HDF5_USE_FILE_LOCKING` to `FALSE`. This can be done in the shell, e.g., with `export HDF5_USE_FILE_LOCKING="FALSE"` on the command line or in a config file (like `.bashrc`), or it can be done in Python as @IdsTeepe shows above: `os.environ["HDF5_USE_FILE_LOCKING"] = "FALSE"`.

**Comment by arjunwadhawan** [comment]
Yep. This works 
Thanks @IdsTeepe for the solution and thanks @dwhswenson for checking.
