### ISSUE TITLE
Unable to write frame to file in branch engines/gromacs/engine.py on branch gromacs_engine

### ISSUE THREAD

**Issue by IdsTeepe** [openpathsampling/openpathsampling#860]
When trying to sample my system I get the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/media/Home/Documents/openpathsampling/openpathsampling/engines/gromacs/engine.py in write_frame_to_file(self, filename, snapshot, mode)
    337             step = np.asarray([0], dtype=np.int32)
--> 338             box = np.asarray([snapshot.box_vectors], dtype=np.float32)
    339             lambd = np.asarray([0.0], dtype=np.float32)

/opt/miniconda3/envs/opsgmx/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 

ValueError: setting an array element with a sequence.
```
Then: `During handling of the above exception, another exception occurred:`, and finally:

```
/media/Home/Documents/openpathsampling/openpathsampling/engines/gromacs/engine.py in write_frame_to_file(self, filename, snapshot, mode)
    342             trr._write(xyz, time, step, box, lambd, vel)
    343         finally:
--> 344             trr.close()
    345             close_file_descriptors(filename)
    346 

UnboundLocalError: local variable 'trr' referenced before assignment
```

When taking a look at the first error by adding the lines:
```
            print(type(snapshot.box_vectors))
            print(snapshot.box_vectors)
            print([snapshot.box_vectors])
```

it is quickly clear what goes wrong. The simple alanine dipeptide example prints:
```
<class 'numpy.ndarray'>
[[2.8038313 0.        0.       ]
 [0.        2.8038313 0.       ]
 [0.        0.        2.8038313]]
[array([[2.8038313, 0.       , 0.       ],
       [0.       , 2.8038313, 0.       ],
       [0.       , 0.       , 2.8038313]], dtype=float32)]
```
whereas my system prints:
```
<class 'simtk.unit.quantity.Quantity'>
[[6.97692 0.      0.     ]
 [0.      6.69292 0.     ]
 [0.      0.      6.35193]] nm
[Quantity(value=array([[6.97692, 0.     , 0.     ],
       [0.     , 6.69292, 0.     ],
       [0.     , 0.     , 6.35193]], dtype=float32), unit=nanometer)]
```

So it seems sometimes the type of this variable is different from what is expected.
Introducing this simple hacky fix:
```
            if type(snapshot.box_vectors).__name__ == "Quantity":
                snapshot.box_vectors = snapshot.box_vectors._value
```

We then get the following error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/media/Home/Documents/openpathsampling/openpathsampling/engines/gromacs/engine.py in write_frame_to_file(self, filename, snapshot, mode)
    342             lambd = np.asarray([0.0], dtype=np.float32)
--> 343             vel = np.asarray([snapshot.velocities], dtype=np.float32)
    344             trr = TRRTrajectoryFile(filename, mode)

/opt/miniconda3/envs/opsgmx/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 

ValueError: setting an array element with a sequence.
```
Which is caused by the same issue.  Applying the same fix for the velocities, everything seems to work fine (the sampler is still running as of now).

If you want to reproduce this error: The [.gro, .top and .trr files](https://drive.google.com/file/d/1jKNwogpDWnTeXKy1XqhkDirqMpiPk9kN/view?usp=sharing) that are used for sampling are made with GROMACS 2018.3. Perhaps more importantly, the initial trajectory is obtained with `trajectory = openpathsampling.engines.openmm.tools.ops_load_trajectory('ca5.trr', top='ca5.gro')`

I can imagine it would be better to check the unit of this quantity class, and to convert the values to those corresponding to ops' internal units. Thus, I will leave this issue open for now.

Finally: During error catching an `UnboundLocalError` is thrown for `trr.close()`, as the variable `trr` is never assigned. Though I think this should never happen anyway, you could catch it with a nested try:
```
        finally:
            try:
                trr.close()
            except UnboundLocalError as e:
                logger.error(e)
            close_file_descriptors(filename)
```
It might be preferred to just not catch the error though.

**Comment by dwhswenson** [comment]
As you observed, the basic problem here is in mixing snapshots from different engines. That's not expected to always be trivial: Snapshot types are specific to their engines; the OpenMM engine returns one type, and the Gromacs engine returns another. Interoperability isn't guaranteed, and wouldn't even make sense between some engines (how would the toy engine run alanine dipeptide?)

I would recommend going through the file system. I think what you need are two functions, `paths.engine.gromacs.load_trr` (which I'll add to the `gromacs_engine` branch) and a function that writes a TRR from a trajectory based on OpenMM snapshots. That one I won't add to the core unless this becomes a more frequent problem (in general, we recommend writing to file by way of MDTraj; unfortunately, the public API of MDTraj doesn't write velocities, and I assume you'll want that in this case.)

This may take some time for me to implement cleanly (as in, I probably won't get to it today, and maybe not tomorrow). You might be able to hack together something that works based on `snapshot_from_gro` (for loading) and by using the `GromacsEngine.write_frame_to_file` as the basis for writing the trajectory. You can compare types, etc., with the MDTraj tests for writing TRR files with velocities: https://github.com/mdtraj/mdtraj/blob/11f33d99ce037239ecd5dca8a9bed2154b1b0854/tests/test_trr.py#L275-L298

**Comment by dwhswenson** [comment]
> Finally: During error catching an `UnboundLocalError` is thrown for `trr.close()`, as the variable `trr` is never assigned. Though I think this should never happen anyway, you could catch it with a nested try:

You solution is a good one, but I've updated the branch with what I think is an even better solution. The try/finally block is to ensure that the file gets closed, even if an error occurs in the `try` part (the error will get passed back to calling code to handle it.) None of the stuff about converting to the right kind of array matters for that, so I moved it to before the `try` block. (Now the error you're seeing should get raised without ever opening the TRR file.)

General guideline in software development: `try` blocks should be as short as possible, aiming to only catch specific errors. The reason for that is exactly what you observed here. I'm glad it didn't cause too much confusion!

**Comment by IdsTeepe** [comment]
Thank you for the detailed answer! it is nice to read up on coding guidelines, and I'm happy that my error got a try block to be a little smaller. 

I'm still left with differing snapshots, but for now allowing two snapshots in the storage and typecasting their contents works fine. I'm looking forward to seeing a new `paths.engine.gromacs.load_trr` function to properly load in my data, though. But there is no hurry ;)
> ... and a function that writes a TRR from a trajectory based on OpenMM snapshots. 
I'm not sure whether I need this function myself. The TRR that i'm using right now has been generated by GROMACS, and I haven't used OpenMM as of yet. If you're not planning on adding it to the core, it might be unnecessary to write the function.
