### ISSUE TITLE
Multiple snapshot types cause KeyError in snapshot_wrapper.py on branch gromacs_engine

### ISSUE THREAD

**Issue by IdsTeepe** [openpathsampling/openpathsampling#861]
[This error](https://github.com/openpathsampling/openpathsampling/files/3677042/snapshot_error.txt) occurs in `openpathsampling/storage/stores.snapshot_wrapper.py` when trying to run a sampler for my system.

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/media/Home/Documents//openpathsampling/openpathsampling/storage/stores/snapshot_wrapper.py in _save(self, obj, n_idx)
    384             print(dict(obj.engine.descriptor)["class"])
--> 385             store, store_idx = self.type_list[obj.engine.descriptor]
    386             self.vars['store'][n_idx // 2] = store_idx

KeyError: SnapshotDescriptor({('n_spatial', 3), ('n_atoms', 29428), ('class', <class 'openpathsampling.engines.gromacs.engine.ExternalMDSnapshot'>)})

During handling of the above exception, another exception occurred:
```
etc..

When trying to get the store from self.type_list, an error is thrown as the snapshot type `ExternalMDSnapshot` is not present.
Normally, it then gets added to the self.type_list in the following code:
```
390        except KeyError:
391            # there is no store yet to handle the given type of snapshot
392            mode = self.treat_missing_snapshot_type
393            if mode == 'create' or \
394                    (mode == 'single' and
395                             len(self.storage.dimensions['snapshottype']) == 0):
396                # we just create space for it
397                store, store_idx = self.add_type(obj.engine.descriptor)
```
In this case, `mode` is `'single'`, but the storage is not empty and thus ` len(self.storage.dimensions['snapshottype'])` is not 0.

By adding the line `print(dict(obj.engine.descriptor)["class"])` to the function I was able to see what went wrong:
When calling
```
sampler = paths.PathSampling(storage=paths.Storage("ca5_test.nc", "w", template),
                             move_scheme=scheme,
                             sample_set=initial_conditions)
```
the function is called and a `<class 'openpathsampling.engines.openmm.snapshot.Snapshot'>` type is added to `self.type_list`. 
This throws no errors, as everything runs smoothly. However, after calling `sampler.run()` afterwards a different snapshot with type `<class 'openpathsampling.engines.gromacs.engine.ExternalMDSnapshot'>` is passed. 

I seem to be able to bypass the error by just allowing two types in the list:
```
393            if mode == 'create' or \
394                    (mode == 'single' and
395                             len(self.storage.dimensions['snapshottype']) <=1):
396                # we just create space for it
397                store, store_idx = self.add_type(obj.engine.descriptor)
```
However, it seems to me that there is a reason behind this check. Why is only one type of snapshot allowed? Does it hurt to allow two types of snapshots (in this case)?

P.S.:
The system is the same as in [this issue](https://github.com/openpathsampling/openpathsampling/issues/860). My guess is also in this case that the differing snapshot types are caused by my loading of the trajectory with `trajectory = tools.ops_load_trajectory('ca5.trr', top='ca5.gro')`.

**Comment by dwhswenson** [comment]
This is deep within @jhprinz's code for storage, so he can probably help better than I can, although he is rarely available to answer things. I suspect that, as you say and as with #860, the fundamental problem is with mixing snapshots between two engines when they're not expected to mix, and the best solution is to go through the file system.

Think of storage as containing shelves ("stores") of a certain size. An OpenMM snapshot with a certain number of atoms requires a certain size, so we make a shelf that can fit those snapshots. The check you're seeing is to ensure that the snapshot is the same size (and type) and type as the one that the shelf is for. Note that the error message gives advice on how to fix it: `Try adding the snapshot type using .add_type(snapshot).` (I assume that's for the store, i.e., `storage.snapshots.add_type(snapshot)`) I don't know why JHP didn't allow auto-registration of new snapshot types.

I suspect the code you're seeing was written before we guaranteed that all snapshots carried an `engine` attribute to identify the engine that created them, which may be part of the reason for that check. A better check now is to ensure that there's a "shelf" for snapshots from each engine. (The new storage subsystem I'm working on does that, and should support auto-registration of new snapshot types.)

The `ExternalMDSnapshot` should only require a much smaller storage space: the .nc file only stores the TRR file name and the snapshot number within that TRR file; the actual data is in the TRR (however, there's significant overhead for the .nc file -- I see similar .nc file sizes for the AD equilibration and a 200-step production run). Note that this means you shouldn't move or delete TRR files from the directory where they are stored! You'll also have to ensure that your working directory is the same (relative to the TRR files) when you do the analysis as when you run the simulation.

**Comment by IdsTeepe** [comment]
Thank you! 
As far as I can see, mixing (these) snapshot types causes no further error. Furthermore, it might not be intended but increasing the type_list length limit is the easiest, and practically results in `store, store_idx = self.add_type(obj.engine.descriptor)` being called once more.
