### ISSUE TITLE
Gromacs engine fails to read steps beyond frame 3041

### ISSUE THREAD

**Issue by IdsTeepe** [openpathsampling/openpathsampling#863]
When running a sampler with engine options `'n_frames_max': 5000` and `'n_steps_per_frame': 5000` I have stumbled upon a hanging simulation quite often by now. OPS simply doesn't send a `SIGINT` (or any signal) to GROMACS, which continues running the step. Taking a look in the `ops_output.log` file, there's just the line:
```
(INFO)openpathsampling.engines.dynamics_engine: Through frame: 3040
```
and the process hangs indefinitely. Setting the logger level to DEBUG it seems that the script gets stuck on GROMACS engine's `read_frame_from_file()`:

```
(INFO)openpathsampling.engines.dynamics_engine: Through frame: 3039
(DEBUG)openpathsampling.engines.external_engine: Looking for frame 3041
(DEBUG)openpathsampling.engines.gromacs.engine: Reading file ./T4L_trr/0000014.trr frame 3040 (of 3040)
(DEBUG)openpathsampling.engines.gromacs.engine: Expected exception caught: TRR Seek out of bounds: given absolute position: 3040
(DEBUG)openpathsampling.engines.external_engine: Sleeping for 5631.90ms
(DEBUG)openpathsampling.engines.gromacs.engine: Reading file ./T4L_trr/0000014.trr frame 3040 (of 3041)
(DEBUG)openpathsampling.engines.gromacs.engine: Creating snapshot
(DEBUG)openpathsampling.engines.external_engine: Found frame 3041
(DEBUG)openpathsampling.ensemble: Starting Suffix._alter
(DEBUG)openpathsampling.ensemble: Checking cache....
(DEBUG)openpathsampling.ensemble: start_frame 46924142658840
(DEBUG)openpathsampling.ensemble: prev_last 46924169839224
(DEBUG)openpathsampling.ensemble: prev_last_idx 3039
(DEBUG)openpathsampling.ensemble: SuffixTrajectory was not reset
(DEBUG)openpathsampling.ensemble: Checking cache....
(DEBUG)openpathsampling.ensemble: start_frame 46924155346304
(DEBUG)openpathsampling.ensemble: prev_last 46924169839224
(DEBUG)openpathsampling.ensemble: prev_last_idx 0
(DEBUG)openpathsampling.ensemble: len(traj)=4288cache_from=-1
(DEBUG)openpathsampling.ensemble: Beginning can_prepend with ens_num:1  ens_final:2  subtraj_final 4287; strict=False
(DEBUG)openpathsampling.ensemble: Cache contents: {'ens_num': 1, 'ens_from': 2, 'subtraj_from': -1, 'assignments': {2: slice(-1, None, None), 1: slice(-4287, -1, None)}}
(DEBUG)openpathsampling.ensemble: cache.prev_start_frame: 4287
(DEBUG)openpathsampling.ensemble: Ensemble 0 : IntersectionEnsemble
(DEBUG)openpathsampling.ensemble: Ensemble 1 : AllOutXEnsemble
(DEBUG)openpathsampling.ensemble: Ensemble 2 : IntersectionEnsemble
(DEBUG)openpathsampling.ensemble: *Traj slice 0 4287 / 4288
(DEBUG)openpathsampling.ensemble: Checking cache....
(DEBUG)openpathsampling.ensemble: start_frame 46924155346232
(DEBUG)openpathsampling.ensemble: prev_last 46924169839224
(DEBUG)openpathsampling.ensemble: prev_last_idx 0
(DEBUG)openpathsampling.engines.gromacs.engine: Reading file ./T4L_trr/0000014.trr frame 3040 (of 3041)
(DEBUG)openpathsampling.ensemble:  Traj slice 0 4287 / 4288
(DEBUG)openpathsampling.ensemble: 1 : (0,4287)
(DEBUG)openpathsampling.ensemble: Assigning frames 0 through 4287 to ensemble 1
(DEBUG)openpathsampling.ensemble: Cache assignments: {2: slice(-1, None, None), 1: slice(-4288, -1, None)}
(DEBUG)openpathsampling.ensemble: Setting cache | ens_num 1 | ens_from 2 | subtraj_from -1
(DEBUG)openpathsampling.ensemble: Cache is Trusted: True
(DEBUG)openpathsampling.ensemble: Moving to the next ensemble 0
(DEBUG)openpathsampling.ensemble: *Traj slice -1 0 / 4288
(DEBUG)openpathsampling.ensemble: Combination is IntersectionEnsemble
(DEBUG)openpathsampling.ensemble: Combination.can_prepend: AllInXEnsemble is True
(DEBUG)openpathsampling.ensemble: LengthEnsemble.can_append: Segment length 0 < 1 : True
(DEBUG)openpathsampling.ensemble: Combination.can_prepend: LengthEnsemble is True
(DEBUG)openpathsampling.ensemble: Combination should return True
(DEBUG)openpathsampling.ensemble: LengthEnsemble.can_append: Segment length 0 < 1 : True
(DEBUG)openpathsampling.ensemble: 0 : (0,0)
(DEBUG)openpathsampling.ensemble: prev_slice slice(-4288, -1, None)
(DEBUG)openpathsampling.ensemble: prev_subtraj Trajectory[4287]
(DEBUG)openpathsampling.ensemble: traj Trajectory[4288]
(DEBUG)openpathsampling.ensemble: Checking cache....
(DEBUG)openpathsampling.ensemble: start_frame 46924155346232
(DEBUG)openpathsampling.ensemble: prev_last 46924169839336
(DEBUG)openpathsampling.ensemble: prev_last_idx 0
(DEBUG)openpathsampling.ensemble: Premature promotion: returning to ensemble 1
(DEBUG)openpathsampling.ensemble: (first, final)(0, 0)
(DEBUG)openpathsampling.ensemble: Setting cache | ens_num 1 | ens_from 2 | subtraj_from -1
(DEBUG)openpathsampling.ensemble: Cache is Trusted: True
(DEBUG)openpathsampling.ensemble: All frames assigned, more ensembles to go: returning True
(INFO)openpathsampling.engines.dynamics_engine: Through frame: 3040
(DEBUG)openpathsampling.engines.external_engine: Looking for frame 3042
(DEBUG)openpathsampling.engines.gromacs.engine: Reading file ./T4L_trr/0000014.trr frame 3041 (of 3041)
(DEBUG)openpathsampling.engines.gromacs.engine: Expected exception caught: TRR Seek out of bounds: given absolute position: 3041
(DEBUG)openpathsampling.engines.external_engine: Sleeping for 5631.95ms
(DEBUG)openpathsampling.engines.gromacs.engine: Reading file ./T4L_trr/0000014.trr frame 3041 (of 3042)
(DEBUG)openpathsampling.engines.gromacs.engine: Received partial frame for ./T4L_trr/0000014.trr 3042
(DEBUG)openpathsampling.engines.gromacs.engine: Reading file ./T4L_trr/0000014.trr frame 3041 (of 3042)
(DEBUG)openpathsampling.engines.gromacs.engine: Received partial frame for ./T4L_trr/0000014.trr 3042
(DEBUG)openpathsampling.engines.gromacs.engine: Reading file ./T4L_trr/0000014.trr frame 3041 (of 3042)
(DEBUG)openpathsampling.engines.gromacs.engine: Received partial frame for ./T4L_trr/0000014.trr 3042
(DEBUG)openpathsampling.engines.gromacs.engine: Reading file ./T4L_trr/0000014.trr frame 3041 (of 3042)
(DEBUG)openpathsampling.engines.gromacs.engine: Received partial frame for ./T4L_trr/0000014.trr 3042
(DEBUG)openpathsampling.engines.gromacs.engine: Reading file ./T4L_trr/0000014.trr frame 3041 (of 3042)
(DEBUG)openpathsampling.engines.gromacs.engine: Received partial frame for ./T4L_trr/0000014.trr 3042
(DEBUG)openpathsampling.engines.gromacs.engine: Reading file ./T4L_trr/0000014.trr frame 3041 (of 3042)
(DEBUG)openpathsampling.engines.gromacs.engine: Received partial frame for ./T4L_trr/0000014.trr 3042
(DEBUG)openpathsampling.engines.gromacs.engine: Reading file ./T4L_trr/0000014.trr frame 3041 (of 3042)
                                                ......
```

So,  `engines.gromacs.engine.read_frame_from_file()` is called and keeps on throwing a `RuntimeError`, 
```
        except RuntimeError as e:
            # TODO: matches "TRR read error"
            logger.debug("Received partial frame for %s %d", file_name,
                         frame_num+1)
            return 'partial'
```
returning `'partial' to engines.external_engine.generate_next_frame(), which handles it as follows:
```
            try:
                next_frame = self.read_frame_from_file(self.output_file,
                                                       self.frame_num)
                                                ......
            if next_frame == "partial":
                time.sleep(0.001) # wait a millisec and rerun
``` 
To me, it seems that the RuntimeError is caused by something different and unexpected in this case. Ideally, the underlying issue is resolved, but as of now no signs of a serious error are given, and I think there should be some maximum number of retries built in.
Another function which calls `gromacs.engine.read_frame_data()` is `gromacs.ExternalMDSnapshot.load_details()`, and tries to catch a `RecursionError`. Is this perhaps related?
An easy way to bypass this problem is by setting  `'n_frames_max'` to `3000`, but this is far from ideal. Any run that is started with  `'n_frames_max': 5000` will eventually silently get stuck in this loop, sometimes after a few days.
Let me stress: This exact issue has happened multiple times on different clusters, always getting stuck at the very same frame. I have not tried with multiple systems yet (as I'm only working on one), but it is not an isolated issue.
I'll try keeping a run in the background to print more information about the `RuntimeError` and update the post if I find something new.

**Comment by dwhswenson** [comment]
Yeah, might be a recursion thing based on the number of steps; I'll check for why later.

Python has a built-in recursion depth limit, which is 3000 by default in Python 3.7. So a frame number around 3000 seems a bit suspicious (would be more so if it was exactly 3000). Try changing the Python recursion limit: https://docs.python.org/3/library/sys.html#sys.setrecursionlimit

Hopefully that will at least be a temporary fix (definitely a step toward diagnosis of the problem). In principle, I didn't intend for the engine to be recursive, so I'll have to figure out why it is. 

The check for recursion in the other function is to catch and re-raise in case loading snapshot information fails over and over again, which would mean something was probably wrong with the file itself. (That function calls itself if there's an index error.) That an unrecoverable error, and probably isn't the case here (it would mean your trr file is corrupt, and doing so on the same frame every time).

**Comment by dwhswenson** [comment]
Oh, and check that your mdp file has a number of steps that corresponds to at least 5000 frames (of course, the mdp lists it in steps, so you'll have to convert that to frames based on the output frequency). If the Gromacs process stops, OPS wouldn't know, and would keep looking for the next frame. I would expect it to see no frame there, not a partial, but still work checking this. (This may be a thing I should add a check for; I think that can be done by checking the status of the subprocess that the engine launches.)

To be clear, if OPS's maximum frames is MORE than the length of the trajectory indicated by the mdp file, Gromacs will terminate normally, and OPS will get confused (since we expect to be responsible for terminating the Gromacs process).

**Comment by dwhswenson** [comment]
I just added a check to ensure that the subprocess is still running if a partial frame is returned (e2dd1c2) . This check already existed if no start to a frame could be identified, but it's possible that for some reason we're identifying a partial frame instead of no frame at all (I've had trouble getting Gromacs files to consistently give me the error I expect, although usually it was with getting "no start to the frame" when it should have said "partial frame found"; this would be vice versa.)

**Comment by IdsTeepe** [comment]
> Python has a built-in recursion depth limit, which is 3000 by default in Python 3.7. So a frame number around 3000 seems a bit suspicious (would be more so if it was exactly 3000). Try changing the Python recursion limit:

I was thrown off-track by reading the `RecursionError` in the same script, but this is no recursion. The script is just stuck in a `while not next_frame_found` loop in `engines.external_engine.generate_next_frame()`. So, a simple incrementing variable (maybe specifically in the 'partial' if-statement) can check the amount of times the loop has run, and terminate after ~100 tries.

> Oh, and check that your mdp file has a number of steps that corresponds to at least 5000 frames

I first had it on 5000 frames exactly (correctly converted), but already put it on 50000 for good measure. Still: same result. And I can verify: gromacs was still running. I decided to kill it manually.

**Comment by dwhswenson** [comment]
> So, a simple incrementing variable (maybe specifically in the 'partial' if-statement) can check the amount of times the loop has run, and terminate after ~100 tries.

In principle, something like this, plus a custom error, could be similar to how we handle the fact that OpenMM occasionally tosses out `NaN` (an effect of mixed precision, IIRC). That means we treat it as a rejected trial. But I'd like to know why you're getting the error before doing that. And if you get it every 14 MC steps, then I wouldn't trust the statistics of your trajectories (error-based rejections -- max length or invalid trajectory/NaN, really shouldn't be more than 5% of your MC trials, and ideally far less!)

Maybe this is a memory error? How many atoms in your system? I thought the seek function in MDTraj would avoid memory usage, but if not, we have 8 bytes/float * 6 floats/atom (xyz, vel) * n_atoms * n_frames. If n_frames ~3000 when this crashes, that's 144kB per atom for 3k frames. If you're limited to 8GB RAM, and you're getting up around 50k atoms, that might be the problem.

But I really thought the seek function was proper random access of the file itself, which avoids loading other parts of the file into memory. And the code seems right to me, at least at a first glance.

Another thing to check: Manually create a snapshot. With the engine you've already defined as `engine`, and the trajectory you already have (e.g., `T4L_trr/0000014.trr` in your example above), try something like the following

```python
snap = paths.engines.gromacs.ExternalMDSnapshot(
    file_name='./T4L_trr/0000014.trr',
    file_position=3042,
    engine=engine
)
snap.load_details()
```

The first part should go fine; it only interacts with the file system when it loads the details (which you can also trigger with `snap.xyz`, `snap.velocities`, etc.). That's where we expect to see the error.

**Comment by dwhswenson** [comment]
Wait. OPS holds everything in memory, so if memory is the problem, it's on us. I haven't added in the ability for OPS to forget the existing coordinates/velocities during trajectory generation.

I hadn't added it yet because I want a clean way, ideally one that handles multiple use cases (the same thing should be done when calculating CVs) However, I think I have a quick and dirty hack that may fix it; note that this is *not* going into the core code yet because it really needs a cleaner approach. Also this absolutely *requires* that you use `cv.enable_diskcache()` (or whatever the exact command is) on any CV that needs to directly access the snapshot data, otherwise you may have this error in analysis. The hack would look something like this (untested, but should give the idea):

```python
# in openpathsampling/engines/dynamics_engine.py:488; DynamicsEngine.iter_generate()
errors = []

# new code starts here
for snap in initial:
    try:
        snap.clear_cache()  # clears details of `ExternalMDSnapshot`s
    except AttributeError:
        pass  # ignore errors from all other kinds of snapshots
# new code ends here

while not valid and final_error is None:
```

**Comment by IdsTeepe** [comment]
> Maybe this is a memory error? How many atoms in your system?

That may very well be! given 6 floats, 8 bytes each, 29428 atoms in my system I get `8*6*29428*3040` = 3.9992GB, 4.0005GB on the next frame. Certainly not the hardware limit but a very suspicious number.

**Comment by dwhswenson** [comment]
Just checking in on this: did the little snippet I suggested fix the problem? Or has it otherwise ceased to be a problem?

**Comment by IdsTeepe** [comment]
Ever since I implemented the snippet, I haven't had runs exceed the 3040 frames limit. I also haven't gone and tested it manually, so I'm not sure if it works yet. Practically speaking it has ceased to be a problem for me, however.

One thing: Placing the snippet in the code block where you suggested:
>`# in openpathsampling/engines/dynamics_engine.py:488; DynamicsEngine.iter_generate()`

I believe it only gets called at the start of a new trajectory. Wouldn't it need to be inside the `while not stop:`-loop at `dynamics_engine.py:529`?

**Comment by sefalkner** [comment]
Do you have the most recent mdtraj version?

I fixed a bug where the offsets of TRR trajectories were wrong . That basically lead to a crash of the trr read function if the trajectories got too large. This gave these partial frame errors or seek out of bounds errors in OPS. The errors occurred always at a certain frame depending on your trajectory size.

https://github.com/mdtraj/mdtraj/issues/1533

**Comment by dwhswenson** [comment]
Sounds like this has been fixed, possibly upstream in MDTraj. I'll leave this around for 72 hours, in case there's any need, closing no earlier than Saturday 17 October 17:00 GMT (19:00 my local).
