### ISSUE TITLE
Python 3.8 testing plans

### ISSUE THREAD

**Issue by dwhswenson** [openpathsampling/openpathsampling#864]
Python 3.8 has been released (although at this moment, not even conda-forge is serving it up). We plan to officially support Python 3.8 as soon as we can run our test suite on Python 3.8. We will maintain Python compatibility based on [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html), meaning that we'll continue testing against Python 3.6 until at least 23 June 2020, after which point Python 3.6 support is no longer guaranteed. (Python 2.7 support will be dropped whenever OPS 2.0 is released in the first half of 2020.)

Here's a checklist of OPS testing requirements and whether we can install them into a Python 3.8 environment (empty at the moment of writing because I can't even create a non-pre-release Python 3.8 environment):

- [x] python
- [x] numpy
- [x] netcdf4
- [x] ujson
- [x] future
- [x] matplotlib
- [x] pyemma
- [x] openmmtools
- [x] networkx
- [x] scipy
- [x] setuptools
- [x] svgwrite
- [x] mdtraj
- [x] pandas
- [x] openmm
- [x] jupyter
- [x] nose
- [x] pytest
- [x] pytest-cov
- [x] python-coveralls* (switching from coveralls to python-coveralls)
- [ ] ipynbtest

**Comment by sroet** [comment]
> We plan to officially support Python 3.8 as soon as we can run our test suite on Python 3.8.

Test run on python 3.8 is feasible at this moment (with skips for optional dependencies like `openmm` and `openmmtools`)

**Comment by dwhswenson** [comment]
We actually distribute on 3.8 because conda-forge handles that automatically. I don't feel like managing different dependency installation procedures for different versions of Python, so I'm letting this sit.

**Comment by dwhswenson** [comment]
At this point the only thing blocking Python 3.8 (and 3.9) is ipynbtest. I think we'll move the tested notebooked over to nbval instead -- I prefer the output from ipynbtest, but since it isn't maintained, better to use the maintained code.
