### ISSUE TITLE
TIS simulation not running on OPS 1.0

### ISSUE THREAD

**Issue by arjunwadhawan** [openpathsampling/openpathsampling#872]
I have a TIS setup which works for OPS 0.9.3 but when I rerun the same simulation on OPS 1.0 it hangs with the attached error (with the TIS setup file).
Initial trajectory is valid for the ensemble being sampled and the order parameter is also valid. 
Bit confused about why engine cannot start simulating 
[TIS_stoppping.zip](https://github.com/openpathsampling/openpathsampling/files/3824528/TIS_stoppping.zip)

Following are my versions of engine and OPS

openmm                    7.4.0           py27_cuda101_rc_1    omnia
openmmtools               0.16.0                   py27_0    omnia
openpathsampling          1.0                      py27_0    omnia

Probably I am missing out something simple and cant see it

**Comment by dwhswenson** [comment]
Is this a duplicate of #837?

In any case, I don't see anywhere that you validate that the old trajectory does, in fact, satisfy the ensemble. The advice there (use the `trajectory_summary` function of the `TISEnsemble`) will still be relevant.

**Comment by arjunwadhawan** [comment]
Hi David 
No, I checked this is not a duplicate it.
The old trajectory does validate the ensamble as this is how my initial trajectory looks like this
![image](https://user-images.githubusercontent.com/21062948/68483386-c0408000-023b-11ea-9dfa-0bedec1324a6.png)

My state definitions are 
State A: lambda_min=-201, lambda_max=-200
State B: lambda_min = -93, lambda_max = -91

This can also be seen in the log file where one line 1437 it says 
![image](https://user-images.githubusercontent.com/21062948/68483957-ba976a00-023c-11ea-8a34-65338b5f50ff.png)

**Comment by dwhswenson** [comment]
It looks like there's some problem with storage. Try to make your example more minimal. Take the things you create and save them to the new storage, one at a time (`storage.save(thing)` will work). That will tell you which object is causing the problem.

**Comment by dwhswenson** [comment]
@arjunwadhawan : Can this be closed?

**Comment by arjunwadhawan** [comment]
Hi @dwhswenson , thanks for the reminder. 
I got busy with other calculation and abandoned this simulation. I will close this in 1 day

**Comment by arjunwadhawan** [comment]
closing this as of now as I cant reproduce the error because my GPU are busy
