### ISSUE TITLE
Unable to export rejected trajectories to mdtraj.Trajectory on gromacs_engine

### ISSUE THREAD

**Issue by IdsTeepe** [openpathsampling/openpathsampling#878]
Let's say I have a variable `storage` with some accepted steps and some rejected steps. If I want to export all accepted steps to trr files, I might write a code block like this:
```
for step in storage.steps:
    if step.change.accepted:
        index = step.idx(storage)
        traj = step.active[0].trajectory.to_mdtraj()
        traj.to_trr(f'prefix_{index:03d}.trr')
```
And that works fine. Recently however, I have tried to export the rejected trajectories for some analysis. [As all my steps have a unique sample associated with them](https://github.com/openpathsampling/openpathsampling/issues/868#issue-510723127), I thought of writing a very similar code block:
```
for step in storage.steps:
    if not step.change.accepted:
        index = step.idx(storage)
        traj = storage.samples[index].trajectory.to_mdtraj()
        traj.to_trr(f'prefix_{index:03d}.trr')
```
However, here, something goes wrong with exporting the box vectors:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/10433791/ops/openpathsampling/openpathsampling/engines/trajectory.py", line 564, in to_mdtraj
    box_vectors = self.box_vectors
  File "/home/10433791/ops/openpathsampling/openpathsampling/engines/trajectory.py", line 144, in __getattr__
    np.copyto(out[idx], getattr(s, item)._value)
AttributeError: 'numpy.ndarray' object has no attribute '_value'
```
[Now I recognize this error](https://github.com/openpathsampling/openpathsampling/issues/860#issue-500902728), and it has to do with the box vectors sometimes being a `simtk.Quantity` and otherwise being a (3,3,3) `numpy.ndarray`. 

The fix seems to be straightforward; when following the error to `openpathsampling/engines/trajectory.py`, `Trajectory.__getattr__()`, we see an explicit code block for these types in lines 135-171:
```
135:                 if type(first) is u.Quantity:
136:                     inner = first._value
137:                     if type(inner) is np.ndarray:
138:                         dtype = inner.dtype
139: 
140:                         out = np.empty(tuple([len(self)] +
141:                                              list(inner.shape)), dtype=dtype)
142:                         # print(f'inner:{inner}, item:{item}')
143:                         for idx, s in enumerate(list.__iter__(self)):
144:                             # print(f's.item:{getattr(s, item)}')
145:                             np.copyto(out[idx], getattr(s, item)._value)
146: 
147:                         return out * first.unit
148:                     else:
149:                         out = [None] * len(self)
150: 
151:                         for idx, s in enumerate(list.__iter__(self)):
152:                             out[idx] = getattr(s, item)
153: 
154:                         return out
155:                 elif type(first) is np.ndarray:
156:                     dtype = first.dtype
157: 
158:                     out = np.empty(tuple([len(self)] +
159:                                          list(first.shape)), dtype=dtype)
160: 
161:                     for idx, s in enumerate(list.__iter__(self)):
162:                         np.copyto(out[idx], getattr(s, item))
163: 
164:                     return out
165:                 else:
166:                     out = [None] * len(self)
167: 
168:                     for idx, s in enumerate(list.__iter__(self)):
169:                         out[idx] = getattr(s, item)
170: 
171:                     return out
```
And after removing the `._value` on line 144, which threw the error, my loop works fine and I'm able to export the rejected trajectories.

I'm not entirely sure why the original line didn't work, as it seems to me that `getattr(s, item)` is supposed to return a `Quantity` (line 135). However, with this fix the code on line 151 is mirrored (and it works) so it seems alright to me.

**Comment by dwhswenson** [comment]
First, would something like this raise the same errors?

```python
for step in storage.steps:
    if not step.change.accepted:
        index = step.mccycle
        traj = step.change.trials[0].trajectory
        traj.to_trr(f'prefix_{index:03d}.trr')
```

The main change is to use `step.change.trials`, but also note that you probably want `step.mccycle`, which is guaranteed to be the step number even if, for example, you restart the simulation and continue in a new file.

Second, it looks like our tests include coverage for the line you change, which means that somewhere, something is expecting the current output. (Jan-Hendrik didn't write unit tests for most of his code, but sometimes things get covered by small-scale integration tests.) So I'm not sure that it is safe to make that change in general.

Overall, `Trajectory.__getattr__` is pretty messy. I think the better solution is to rewrite it, using ideas from the snapshot "features" to add special cases for engines that return quantities with units. I'll start working on that.

**Comment by IdsTeepe** [comment]
> First, would something like this raise the same errors?

This would raise:
`AttributeError: 'Trajectory' object has no attribute 'to_trr'`. 
Note that the error occurs when exporting with `Trajectory.to_mdtraj()`, prior to using `mdtraj.Trajectory.to_trr()`.

That being said, the following code block
```py
for step in storage.steps:
    if not step.change.accepted:
        index = step.mccycle
        traj = step.change.trials[0].trajectory
        traj.to_mdtraj()
```
(with `to_mdtraj()` instead of `to_trr()`) gives the same error, and I can confirm that `step.change.trials[0].trajectory` (albeit more cleanly) results in the same trajectory as `storage.samples[step.idx(storage)].trajectory`

**Comment by dwhswenson** [comment]
Sorry -- yes, I definitely meant to do the `to_mdtraj()` first! Oops!

I've put up PR  #879 that I hope will solve the problem. The easiest way to check (since #879 doesn't include the Gromacs engine branch) is either (a) you create a local branch that merges those two together; or (b) copy-paste the new `Trajectory.__getattr__` into your current code (which is easier depends on how comfortable you are with git). The downside of (b) is that it will break the OpenMM engine (you need to the rest of that PR to have OpenMM work), but I don't think that's a major issue for you.

Once I'm sure it works (and that it doesn't break anything else) I'll merge #879 into master and back into the Gromacs engine branch.

(I'm planning on doing some final reorganization of the Gromacs engine branch and merging it into master in the next week or so -- remaining bugs are probably little things like this, not major showstoppers.)

**Comment by dwhswenson** [comment]
By the way, one thing about the approach you're using here: you're going from an OPS trajectory to an MDTraj trajectory to a TRR file. The MDTraj trajectory does not contain velocities (this is a design decision in MDTraj), so neither will the TRR. If you look in the `GromacsEngine`, you can find how to use the private API in MDTraj that *does* allow you to write TRR files.

**Comment by dwhswenson** [comment]
@IdsTeepe : Have you had a chance to see if #879 fixes this?

**Comment by IdsTeepe** [comment]
I am sorry for not having replied earlier. As of now I still haven't had the chance to check whether the new code fixes the problem, although I do have good faith that it does.
