### ISSUE TITLE
What should snapshot.engine return?

### ISSUE THREAD

**Issue by sroet** [openpathsampling/openpathsampling#904]
Alright, so while trying to continue simulations that crashed due to #892, I ran into some behavior that I wondered if it is intentional:

`snapshot.engine` gives back the engine in it's current state, without updating it (this can be an uninitialized engine after loading a ToyEngine and led to my position modifier crashing out (as it asks for the current potential energy of the engine)

Without thinking to much about it, I expected `snapshot.engine` to return `engine` with `engine.current_snapshot = snapshot`. There is probably some reason for the current behavior but I could not really think of one. 

So therefor my question: should `snapshot.engine` update `engine.current_snapshot` before returning or should it just return the `enigne` in it's current state (even if it is an uninitialized ToyEngine)?

**Comment by dwhswenson** [comment]
No, the expectation is that `snapshot.engine` has no side-effect on the `engine` itself. In most cases, `snapshot.engine` will be the same object in memory that is used elsewhere. Adding side-effects could therefore create confusion elsewhere. Keep in mind that `snapshot.engine` can be used as a trick to get to properties that are calculated by the engine. So you could probably construct a scenario using `snapshot.engine` in a CV that defines a volume in a sequential ensemble, where changing `engine.current_snapshot` would lead to you continuing dynamics from the wrong snapshot!

This is why the OpenMM instantaneous temperature calculation uses the `old_snap` variable to preserve the engine's state: 

https://github.com/openpathsampling/openpathsampling/blob/26997b43745e197abb91cdb3f51916da0cfc1774/openpathsampling/engines/openmm/features/instantaneous_temperature.py#L27-L48

In general, I wouldn't recommend thinking of "the current potential energy of the engine" as having meaning. It should be "the potential energy of the engine's current snapshot." For OpenMM, there's a guarantee that the current snapshot returns the same object in memory if you ask for it more than once in a row. (If toy engine doesn't do that, it should; I would have to check the code.) That means that using it in a function is almost as fast as acting on the internally-stored data, and a lot more future-proofed.

**Comment by sroet** [comment]
thanks for the clarification. I see how changing the state of the engine can lead to undefined behavior. 

> In general, I wouldn't recommend thinking of "the current potential energy of the engine" as having meaning. It should be "the potential energy of the engine's current snapshot."

I think I got thrown for a loop where [PES.V()](https://github.com/openpathsampling/openpathsampling/blob/26997b43745e197abb91cdb3f51916da0cfc1774/openpathsampling/engines/toy/pes.py#L60) works on an engine instead of a snapshot. 
I will update my modifier to use a similar codeblock as you linked.

Closing, thank you for the fast response!

**Comment by dwhswenson** [comment]
> I think I got thrown for a loop where PES.V() works on an engine instead of a snapshot.

I can understand that. Somewhere in the toy engine is a comment about how I should create a separate "system" class for the state information (internal representation of the snapshot), rather than keeping that information in the engine object. I didn't do that when first developing the toy engine out of laziness (or too much other code to write), but this is exactly why I should have.
