### ISSUE TITLE
SyntaxWarning in Python 3.8

### ISSUE THREAD

**Issue by bdice** [openpathsampling/openpathsampling#943]
Hi! I'm looking into using OpenPathSampling. I imported the package while preparing to go through the tutorial and got a SyntaxWarning. This is non-fatal but it's an easy fix and I'll make a PR. This is related to #864 and #871.

```
>>> import openpathsampling
/.../openpathsampling/openpathsampling/engines/features/numpydoctools.py:207: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if section is not 'HEAD':
```

Cause: https://docs.python.org/3/whatsnew/3.8.html#changes-in-python-behavior

**Comment by tirkarthi** [comment]
See also https://github.com/openpathsampling/openpathsampling/issues/945 for some similar warnings
